"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import styles from "./OperationsCenter.module.css";

type Health={status:string;applicationErrorCount:number;staleTelemetryCount:number;failedWebhookCount:number;failedCronCount:number;databaseCapacityPercent:number;storageCapacityPercent:number;unavailableProviderCount:number;openCriticalCount:number;checkedAt:string};
type Event={id:string;signal:string;severity:string;status:string;detail:string;assignedTeam:string;assignedOwner:string;occurrenceCount:number;lastDetectedAt:string;acknowledgeDueAt:string;escalationDueAt:string;escalationLevel:number;runbookUrl:string;resolutionNote:string};
type Escalation={id:string;monitoringEventId:string;level:number;fromTeam:string;toTeam:string;reason:string;deliveryStatus:string;createdAt:string};
type Snapshot={release:string;health:Health|null;events:Event[];escalations:Escalation[];fresh:boolean;status:string};

const fmt=(value:string,locale:string)=>value?new Date(value).toLocaleString(locale):"—";
const metric=(value:number,suffix="")=>value<0?"—":`${value}${suffix}`;

export default function OperationsCenterPage(){
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[language,setLanguage]=useState<"tr"|"en">("tr"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<Event|null>(null),[owner,setOwner]=useState(""),[note,setNote]=useState("");
  const en=language==="en",locale=en?"en-US":"tr-TR";
  const load=useCallback(async()=>{const [ops,platform]=await Promise.all([fetch("/api/operations-center",{cache:"no-store"}),fetch("/api/platform",{cache:"no-store"})]),payload=await ops.json() as Snapshot&{error?:string},platformPayload=await platform.json() as {settings?:Record<string,string>};if(!ops.ok)throw new Error(payload.error||"Operasyon merkezi yüklenemedi.");setSnapshot(payload);setLanguage(platformPayload.settings?.language==="en"?"en":"tr")},[]);
  useEffect(()=>{let active=true;void Promise.all([fetch("/api/operations-center",{cache:"no-store"}),fetch("/api/platform",{cache:"no-store"})]).then(async([ops,platform])=>{const payload=await ops.json() as Snapshot&{error?:string},platformPayload=await platform.json() as {settings?:Record<string,string>};if(!ops.ok)throw new Error(payload.error||"Operasyon merkezi yüklenemedi.");if(active){setSnapshot(payload);setLanguage(platformPayload.settings?.language==="en"?"en":"tr")}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Operasyon merkezi yüklenemedi.")});return()=>{active=false}},[]);
  const action=async(kind:"sweep"|"acknowledge"|"resolve")=>{setBusy(true);setError("");try{const body:Record<string,unknown>={action:kind};if(kind!=="sweep"){body.id=selected?.id;body.note=note;if(kind==="acknowledge")body.owner=owner}const response=await fetch("/api/operations-center",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"İşlem tamamlanamadı.");setSelected(null);setOwner("");setNote("");await load()}catch(cause){setError(cause instanceof Error?cause.message:"İşlem tamamlanamadı.")}finally{setBusy(false)}};
  const openEvents=useMemo(()=>snapshot?.events.filter(item=>item.status!=="RESOLVED")||[],[snapshot]),health=snapshot?.health;
  const metrics=[[en?"Application errors":"Uygulama hataları",health?.applicationErrorCount??-1],[en?"Stale telemetry":"Geciken telemetri",health?.staleTelemetryCount??-1],[en?"Failed delivery":"Webhook / teslimat",health?.failedWebhookCount??-1],[en?"Failed schedules":"Başarısız cron",health?.failedCronCount??-1],[en?"Database capacity":"Veritabanı kapasitesi",health?.databaseCapacityPercent??-1,"%"],[en?"Storage capacity":"Storage kapasitesi",health?.storageCapacityPercent??-1,"%"],[en?"Provider outage":"Sağlayıcı kesintisi",health?.unavailableProviderCount??-1],[en?"Open critical":"Açık kritik",health?.openCriticalCount??-1]] as Array<[string,number,string?]>;
  return <main className={styles.shell}>
    <header className={styles.header}><div><Link href="/">← {en?"Fleet Platform":"Filo Platform"}</Link><span>{en?"PRODUCTION OPERATIONS · V1.28.20":"ÜRETİM OPERASYONU · V1.28.20"}</span><h1>{en?"Monitoring & Operations Center":"İzleme ve Operasyon Merkezi"}</h1><p>{en?"Application, telemetry, delivery, capacity and provider signals with enforced acknowledgement and escalation.":"Uygulama, telemetri, teslimat, kapasite ve sağlayıcı sinyallerini zorunlu onay ve eskalasyonla yönetin."}</p></div><button disabled={busy} onClick={()=>void action("sweep")}>{busy?(en?"Checking…":"Denetleniyor…"):(en?"Run health sweep":"Sağlık taramasını çalıştır")}</button></header>
    {error&&<div className={styles.error} role="alert">{error}</div>}
    <section className={styles.statusBar}><strong className={snapshot?.status==="GO_FOR_OBSERVABILITY_GATE"?styles.good:styles.bad}>{snapshot?.status||"LOADING"}</strong><span>{en?"Last verified":"Son doğrulama"}: {fmt(health?.checkedAt||"",locale)}</span><span>{snapshot?.fresh?(en?"Fresh evidence":"Güncel kanıt"):(en?"Evidence older than 20 min":"Kanıt 20 dakikadan eski")}</span></section>
    <section className={styles.metrics} aria-label={en?"Operational metrics":"Operasyon metrikleri"}>{metrics.map(([label,value,suffix])=><article key={label}><small>{label}</small><strong>{metric(value,suffix)}</strong></article>)}</section>
    <section className={styles.grid}><article className={styles.panel}><header><div><h2>{en?"Alert lifecycle":"Alarm yaşam döngüsü"}</h2><p>{openEvents.length} {en?"open or escalated events":"açık veya eskale alarm"}</p></div></header><div className={styles.tableWrap}><table><thead><tr><th>{en?"Signal":"Sinyal"}</th><th>{en?"Status":"Durum"}</th><th>{en?"Owner":"Sahip"}</th><th>{en?"Last seen":"Son görülme"}</th><th>{en?"Action":"İşlem"}</th></tr></thead><tbody>{snapshot?.events.length?snapshot.events.map(item=><tr key={item.id}><td><b>{item.signal}</b><small>{item.detail}</small></td><td><span className={`${styles.badge} ${styles[item.severity.toLowerCase()]||""}`}>{item.status} · {item.severity}</span><small>L{item.escalationLevel} · ×{item.occurrenceCount}</small></td><td>{item.assignedOwner||item.assignedTeam}</td><td>{fmt(item.lastDetectedAt,locale)}</td><td>{item.status==="RESOLVED"?<small>{item.resolutionNote||"—"}</small>:<button className={styles.secondary} onClick={()=>{setSelected(item);setOwner(item.assignedOwner);setNote("")}}>{en?"Manage":"Yönet"}</button>}</td></tr>):<tr><td colSpan={5}>{en?"No monitoring event yet.":"Henüz izleme olayı yok."}</td></tr>}</tbody></table></div></article>
    <aside className={styles.panel}><header><div><h2>{en?"Escalation history":"Eskalasyon geçmişi"}</h2><p>{en?"Immutable routing evidence":"Değiştirilemez yönlendirme kanıtı"}</p></div></header><div className={styles.timeline}>{snapshot?.escalations.length?snapshot.escalations.slice(0,12).map(item=><div key={item.id}><i>L{item.level}</i><p><strong>{item.fromTeam} → {item.toTeam}</strong><span>{item.reason}</span><small>{fmt(item.createdAt,locale)} · {item.deliveryStatus}</small></p></div>):<p className={styles.empty}>{en?"No escalation recorded.":"Eskalasyon kaydı yok."}</p>}</div></aside></section>
    {selected&&<section className={styles.actionPanel}><div><span>{selected.signal} · {selected.status}</span><h2>{en?"Acknowledge or resolve alert":"Alarmı onayla veya çöz"}</h2><p>{selected.detail}</p></div><label>{en?"Responsible owner":"Sorumlu kişi"}<input value={owner} onChange={event=>setOwner(event.target.value)} placeholder={en?"Name or team":"Ad veya ekip"}/></label><label>{en?"Operational note":"Operasyon notu"}<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder={en?"What was checked and what changed?":"Neyi kontrol ettiniz, ne değişti?"}/></label><div><button className={styles.secondary} onClick={()=>setSelected(null)}>{en?"Cancel":"Vazgeç"}</button><button disabled={busy||owner.trim().length<3||note.trim().length<5} onClick={()=>void action("acknowledge")}>{en?"Acknowledge":"Onayla"}</button><button disabled={busy||note.trim().length<10} onClick={()=>void action("resolve")}>{en?"Resolve":"Çözüldü"}</button></div></section>}
  </main>;
}
