import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { tmpdir } from "node:os";

const root=resolve(import.meta.dirname,"..");
test("operations center covers every required signal and a real alert lifecycle",async()=>{const [policy,source,api,cron,migration]=await Promise.all([readFile(resolve(root,"config/operations-center-policy.json"),"utf8"),readFile(resolve(root,"lib/operations-center.ts"),"utf8"),readFile(resolve(root,"app/api/operations-center/route.ts"),"utf8"),readFile(resolve(root,"app/api/system/operations-tick/route.ts"),"utf8"),readFile(resolve(root,"supabase/migrations/20260828030000_v1_28_18_operations_center.sql"),"utf8")]),config=JSON.parse(policy);for(const signal of config.requiredSignals)assert.match(source,new RegExp(signal));for(const action of ["sweep","acknowledge","resolve"])assert.match(api,new RegExp(action));assert.match(cron,/runOperationsCenterSweep/);assert.match(migration,/FORCE ROW LEVEL SECURITY/);assert.match(migration,/REVOKE ALL/)});
test("final software gates pass without pretending external evidence exists",()=>{const run=spawnSync(process.execPath,[resolve(root,"scripts/validate-final-production-readiness.mjs")],{cwd:root,encoding:"utf8"});assert.equal(run.status,0,run.stderr||run.stdout);const result=JSON.parse(run.stdout);assert.equal(result.softwareStatus,"PASSED");assert.equal(result.status,"SOFTWARE_COMPLETE_EXTERNAL_EVIDENCE_REQUIRED");assert.deepEqual(result.controlledRollout.map(item=>item.trafficPercent),[0,5,25,100])});
test("strict final GO fails closed on the empty evidence template",()=>{const run=spawnSync(process.execPath,[resolve(root,"scripts/validate-final-production-readiness.mjs"),"--strict","--manifest=docs/production-evidence/final-production-acceptance-template.json"],{cwd:root,encoding:"utf8"});assert.notEqual(run.status,0);const result=JSON.parse(run.stdout);assert.equal(result.status,"NO_GO");assert.match(result.blockers.join(" "),/PASSED değil/u)});
test("strict final GO recomputes every evidence hash and validates gate metrics",async()=>{const evidenceRoot=await mkdtemp(resolve(tmpdir(),"filo-final-evidence-"));try{const metrics={OBSERVABILITY:{monitoringHours:24,openCritical:0,deliveryTestPassed:true,maximumSnapshotGapMinutes:15},INDEPENDENT_SECURITY:{critical:0,high:0,tenantIsolationPassed:true,privilegeEscalationPassed:true,rlsBypassPassed:true,uploadAttackPassed:true,owaspAsvsPassed:true,externalAuditor:true},PERFORMANCE_CAPACITY:{concurrentUsers:100,p95Ms:500,p99Ms:1000,errorRatePercent:1,telemetryLoadMeasured:true,monthlyCostMeasured:true},LEGAL_KVKK:{officialLegalApproval:true,locationNoticeApproved:true,retentionDeletionApproved:true,subprocessorsApproved:true},DATA_MIGRATION:{modules:4,rollbackPassed:true,reconciliationMismatchCount:0},PILOT_UAT:{companies:2,vehicles:3,criticalDefects:0,writtenApprovals:2},CONTROLLED_ROLLOUT:{phases:[0,5,25,100],rollbackPlansVerified:true,healthCoveragePassed:true,ownerGo:true}},gates=[];for(const [id,gateMetrics] of Object.entries(metrics)){const relativePath=`${id.toLowerCase()}.txt`,bytes=Buffer.from(`signed external evidence for ${id}`);await writeFile(resolve(evidenceRoot,relativePath),bytes);gates.push({id,status:"PASSED",executedAt:new Date().toISOString(),approver:`Independent ${id} approver`,metrics:gateMetrics,evidence:[{relativePath,sha256:createHash("sha256").update(bytes).digest("hex"),sizeBytes:bytes.length,scanStatus:"CLEAN"}]})}const manifestPath=resolve(evidenceRoot,"manifest.json");await writeFile(manifestPath,JSON.stringify({format:"FILO_FINAL_PRODUCTION_EVIDENCE_V3",release:"1.28.20",environment:"production",gates}));const run=spawnSync(process.execPath,[resolve(root,"scripts/validate-final-production-readiness.mjs"),"--strict",`--manifest=${manifestPath}`,`--evidence-root=${evidenceRoot}`],{cwd:root,encoding:"utf8"});assert.equal(run.status,0,run.stderr||run.stdout);assert.equal(JSON.parse(run.stdout).status,"READY_FOR_OWNER_GO")}finally{await rm(evidenceRoot,{recursive:true,force:true})}});
