import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { crc16Ibm, luhnValid, parseQueclinkLine, parseTeltonikaAvlFrame, parseTeltonikaImeiHandshake, signGatewayBody, validateIccid, validateImei } from "../services/telematics-gateway/src/core.mjs";
import { validateHardwareEvidence } from "../scripts/validate-hardware-gateway-evidence.mjs";

test("IMEI and ICCID use Luhn validation",()=>{assert.equal(validateImei("490154203237518"),true);assert.equal(validateImei("490154203237519"),false);assert.equal(validateIccid("8944500101234567891"),true);assert.equal(luhnValid("not-digits"),false)});
test("Teltonika handshake accepts a provisionable IMEI",()=>{const imei="490154203237518",buffer=Buffer.concat([Buffer.from([0,15]),Buffer.from(imei)]),result=parseTeltonikaImeiHandshake(buffer);assert.equal(result.imei,imei);assert.deepEqual([...result.response],[1])});
test("Teltonika Codec 8E frame validates CRC and returns a device ACK",()=>{const timestamp=1787875200000,data=Buffer.alloc(41);let offset=0;data.writeUInt8(0x8e,offset++);data.writeUInt8(1,offset++);data.writeBigUInt64BE(BigInt(timestamp),offset);offset+=8;data.writeUInt8(0,offset++);data.writeInt32BE(Math.round(29.025*1e7),offset);offset+=4;data.writeInt32BE(Math.round(41.015*1e7),offset);offset+=4;data.writeUInt16BE(42,offset);offset+=2;data.writeUInt16BE(180,offset);offset+=2;data.writeUInt8(9,offset++);data.writeUInt16BE(55,offset);offset+=2;data.writeUInt16BE(0,offset);offset+=2;data.writeUInt16BE(0,offset);offset+=2;for(let index=0;index<5;index++){data.writeUInt16BE(0,offset);offset+=2}data.writeUInt8(1,offset++);assert.equal(offset,data.length);const frame=Buffer.alloc(8+data.length+4);frame.writeUInt32BE(data.length,4);data.copy(frame,8);frame.writeUInt32BE(crc16Ibm(data),8+data.length);const parsed=parseTeltonikaAvlFrame(frame);assert.equal(parsed.codec,"CODEC8E");assert.equal(parsed.recordCount,1);assert.equal(parsed.records[0].latitude,41.015);assert.equal(parsed.records[0].longitude,29.025);assert.equal(parsed.acknowledgement.readUInt32BE(0),1)});
test("CRC and HMAC contracts are deterministic",()=>{assert.equal(crc16Ibm(Buffer.from("010203","hex")),0xa110);assert.equal(signGatewayBody("secret","2026-08-28T00:00:00.000Z","MSG-12345678","{}"),signGatewayBody("secret","2026-08-28T00:00:00.000Z","MSG-12345678","{}"))});
test("Queclink refuses guessed vendor fields",()=>{assert.throws(()=>parseQueclinkLine("+RESP:GTFRI,1,356938035643809$",{status:"VENDOR_PROTOCOL_REQUIRED"}),/QUECLINK_VENDOR_PROFILE_REQUIRED/)});
test("physical template remains NO_GO without external evidence",()=>{const template=JSON.parse(readFileSync(new URL("../docs/production-evidence/hardware-gateway-evidence-template.json",import.meta.url),"utf8")),result=validateHardwareEvidence(template);assert.equal(result.status,"NO_GO");assert.equal(result.passed,false);assert.ok(result.checks.filter(item=>!item.passed).length>=10)});
test("validator accepts a complete real-execution shaped evidence set",()=>{const now=new Date().toISOString(),value={format:"FILO_HARDWARE_GATEWAY_EVIDENCE_V1",version:"1.28.11",environment:"production",procurementApproved:true,approvedBy:"OPERATIONS OWNER",approvedAt:now,selectedDevice:{provider:"TELTONIKA",model:"FMC920",protocol:"CODEC8E",imeiSuffix:"7518",firmware:"03.29.00",realDevice:true},sim:{operator:"PILOT MNO",iccidSuffix:"7891",apn:"iot",realSim:true},gateway:{tcpHostedOutsideVercel:true,mqttTls:true,mqttQos:1,mqttRetained:false,hmacValid:true,duplicateBlocked:true},fieldRun:{startedAt:now,endedAt:now,durationMinutes:480,gatewayBatches:24,expectedTelemetryCount:960,telemetryCount:900,maxGapSeconds:120},scenarios:["LIVE_ROUTE_8H","TCP_RECONNECT","MQTT_REDELIVERY","SIM_OUTAGE_RECOVERY","POWER_CYCLE_RECOVERY","DUPLICATE_FRAME","IGNITION_EVENT"].map(code=>({code,status:"PASSED",realExecution:true})),evidence:["gateway.log","route.csv","photos.zip"].map(fileName=>({fileName,sha256:"a".repeat(64)}))};assert.equal(validateHardwareEvidence(value).status,"GO")});
