import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";

const root=resolve(import.meta.dirname,".."),validator=resolve(root,"scripts/validate-mobile-field-evidence.mjs"),sha="a".repeat(64);
function runFixture(overrides=run=>run){
  const base=(platform,manufacturer,osVersion,scenario,status="PASSED")=>overrides({platform,manufacturer,deviceModel:`${manufacturer}-PHYSICAL`,osVersion,scenario,status,durationMinutes:scenario==="ENDURANCE_8H"?480:120,telemetryCount:scenario==="ENDURANCE_8H"?800:200,maxGapSeconds:120,runtimeEventCount:200,offlineQueueCount:scenario==="OFFLINE_RECONNECT"?20:0,flushedCount:scenario==="OFFLINE_RECONNECT"?40:0,lateTelemetryCount:scenario==="OFFLINE_RECONNECT"?20:0,batterySampleCount:scenario==="ENDURANCE_8H"?32:8,batteryDropPercent:scenario==="ENDURANCE_8H"?18:4,chargingCount:0,queueOverflowCount:0,crashCount:0,permissionLossCount:0,evidenceReference:`evidence://${platform}/${manufacturer}/${osVersion}/${scenario}`,evidenceSha256:sha});
  const runs=[];for(const version of ["IOS 17","IOS 18","IOS 19"]){runs.push(base("IOS","APPLE",version,"BACKGROUND_LOCKED"),base("IOS","APPLE",version,"USER_TERMINATED","LIMIT_DOCUMENTED"))}runs.push(base("IOS","APPLE","IOS 19","OFFLINE_RECONNECT"),base("IOS","APPLE","IOS 19","ENDURANCE_8H"));for(const manufacturer of ["SAMSUNG","XIAOMI","OPPO","PIXEL"])for(const scenario of ["BACKGROUND_LOCKED","OFFLINE_RECONNECT","ENDURANCE_8H","FORCE_STOP"])runs.push(base("ANDROID",manufacturer,"ANDROID 16",scenario,scenario==="FORCE_STOP"?"LIMIT_DOCUMENTED":"PASSED"));return {format:"FILO_MOBILE_FIELD_EVIDENCE_V1",release:"1.28.20",generatedAt:new Date().toISOString(),physicalDevices:true,secretValuesIncluded:false,runs};
}
async function validate(fixture){const directory=await mkdtemp(join(tmpdir(),"filo-mobile-field-")),path=join(directory,"evidence.json");await writeFile(path,JSON.stringify(fixture));const result=spawnSync(process.execPath,[validator,`--evidence=${path}`,"--strict"],{cwd:root,encoding:"utf8"});return {result,output:JSON.parse(result.stdout)}}

test("complete physical iOS and Android matrix is accepted",async()=>{const {result,output}=await validate(runFixture());assert.equal(result.status,0,result.stderr);assert.equal(output.status,"GO_FOR_MOBILE_FIELD_GATE");assert.equal(output.blockerCount,0)});
test("force-stop cannot be presented as a tracking success",async()=>{const {result,output}=await validate(runFixture(run=>run.scenario==="FORCE_STOP"?{...run,status:"PASSED"}:run));assert.notEqual(result.status,0);assert.equal(output.status,"NO_GO");assert.ok(output.checks.some(check=>check.id==="NO_FALSE_TERMINATION_PASS"&&check.status==="BLOCKED"))});
test("battery and queue overflow failures block endurance evidence",async()=>{const {result,output}=await validate(runFixture(run=>run.scenario==="ENDURANCE_8H"?{...run,batteryDropPercent:31,queueOverflowCount:1}:run));assert.notEqual(result.status,0);assert.ok(output.checks.some(check=>check.id==="PASSED_METRICS"&&check.status==="BLOCKED"))});
test("mobile runtime uses measured battery, ordered durable queue and diagnostic ingestion",async()=>{const [driver,store,route,migration,supabaseMigration,policy]=await Promise.all([readFile(resolve(root,"mobile-driver/src/driver-runtime.ts"),"utf8"),readFile(resolve(root,"lib/platform-store.ts"),"utf8"),readFile(resolve(root,"app/api/mobile-runtime/route.ts"),"utf8"),readFile(resolve(root,"drizzle/0013_amusing_jamie_braddock.sql"),"utf8"),readFile(resolve(root,"supabase/migrations/20260828000100_v1_28_11_hardware_gateway_acceptance.sql"),"utf8"),readFile(resolve(root,"config/mobile-field-acceptance-policy.json"),"utf8")]);assert.match(driver,/Battery\.getBatteryLevelAsync/);assert.match(driver,/MAX_QUEUE_ITEMS=10000/);assert.match(driver,/for\(const item of snapshot\)/);assert.match(driver,/catch\{break\}/);assert.match(driver,/QUEUE_OVERFLOW/);assert.match(driver,/pendingStop/);assert.doesNotMatch(driver,/battery:0/);assert.match(store,/recordMobileRuntimeEvent/);assert.match(store,/LIMIT_DOCUMENTED/);assert.match(route,/action==="diagnostic"/);assert.match(migration,/mobile_runtime_events/);assert.match(supabaseMigration,/FORCE ROW LEVEL SECURITY/);assert.match(supabaseMigration,/GRANT SELECT ON public\.mobile_runtime_events/);assert.doesNotMatch(supabaseMigration,/GRANT INSERT ON public\.mobile_runtime_events/);assert.equal(JSON.parse(policy).release,"1.28.20")});

test("mobile and gateway packages are versioned, reproducibly locked and free of the vulnerable xcode uuid",async()=>{const [rootPackageSource,mobilePackageSource,gatewayPackageSource,mobileLockSource,gatewayLockSource]=await Promise.all([readFile(resolve(root,"package.json"),"utf8"),readFile(resolve(root,"mobile-driver/package.json"),"utf8"),readFile(resolve(root,"services/telematics-gateway/package.json"),"utf8"),readFile(resolve(root,"mobile-driver/package-lock.json"),"utf8"),readFile(resolve(root,"services/telematics-gateway/package-lock.json"),"utf8")]),rootPackage=JSON.parse(rootPackageSource),mobilePackage=JSON.parse(mobilePackageSource),gatewayPackage=JSON.parse(gatewayPackageSource),mobileLock=JSON.parse(mobileLockSource),gatewayLock=JSON.parse(gatewayLockSource);assert.deepEqual([rootPackage.version,mobilePackage.version,gatewayPackage.version],["1.28.20","1.28.20","1.28.20"]);assert.equal(mobileLock.packages[""].version,"1.28.20");assert.equal(gatewayLock.packages[""].version,"1.28.20");assert.equal(mobilePackage.overrides?.xcode?.uuid,"11.1.1");assert.equal(mobileLock.packages["node_modules/uuid"].version,"11.1.1")});
