import { runtimeEnv, workspaceForDeviceToken } from "../../../lib/platform-store";
import { assertRequestSize, enforceRateLimit } from "../../../lib/security";

export const dynamic = "force-dynamic";

async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const digest=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
function secureEqual(left:string,right:string){if(left.length!==right.length)return false;let mismatch=0;for(let index=0;index<left.length;index++)mismatch|=left.charCodeAt(index)^right.charCodeAt(index);return mismatch===0}
function errorResponse(error:unknown){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Takip cihazı gateway işlemi başarısız."},{status:500})}

type GatewayPoint={vehicleId?:unknown;latitude?:unknown;longitude?:unknown;speed?:unknown;battery?:unknown;capturedAt?:unknown;eventType?:unknown;sequence?:unknown;accuracy?:unknown;altitude?:unknown;heading?:unknown};

export async function POST(request:Request){
  try{
    assertRequestSize(request,256*1024);const authorization=request.headers.get("authorization")||"",token=authorization.startsWith("Bearer ")?authorization.slice(7).trim():"";if(!token)return Response.json({error:"Gateway cihaz anahtarı zorunludur."},{status:401});
    const device=await workspaceForDeviceToken(token);if(!["TELTONIKA","QUECLINK","GENERIC_HTTP"].includes(device.provider))return Response.json({error:"Bu anahtar fiziksel takip gateway’i için yetkili değildir."},{status:403});
    const messageId=(request.headers.get("x-filo-message-id")||"").trim(),sentAt=(request.headers.get("x-filo-sent-at")||"").trim(),signature=(request.headers.get("x-filo-signature")||"").trim().toLowerCase(),body=await request.text();
    if(!/^[A-Za-z0-9._:-]{8,128}$/.test(messageId))return Response.json({error:"Geçerli x-filo-message-id zorunludur."},{status:400});const timestampMs=Date.parse(sentAt);if(!Number.isFinite(timestampMs)||Math.abs(Date.now()-timestampMs)>5*60*1000)return Response.json({error:"Gateway zaman damgası geçersiz veya süresi dolmuş."},{status:401});if(!signature||!secureEqual(await hmac(token,`${sentAt}.${messageId}.${body}`),signature))return Response.json({error:"Geçersiz gateway imzası."},{status:401});
    const env=runtimeEnv();await enforceRateLimit(env.DB,request,`tracker-gateway:${device.provider}`,600,60,device.deviceId);const payload=JSON.parse(body) as {provider?:unknown;protocol?:unknown;imei?:unknown;vehicleId?:unknown;records?:GatewayPoint[]};if(String(payload.provider||"").toLocaleUpperCase("tr-TR")!==device.provider||String(payload.protocol||"").toLocaleUpperCase("tr-TR")!==device.protocol)return Response.json({error:"Gateway sağlayıcı/protokol profili cihaz anahtarıyla eşleşmiyor."},{status:403});if(!device.imei||String(payload.imei||"")!==device.imei)return Response.json({error:"Gateway IMEI'si aktif donanım atamasıyla eşleşmiyor."},{status:403});const records=Array.isArray(payload.records)?payload.records:[];if(!records.length||records.length>100)return Response.json({error:"Gateway paketi 1-100 konum kaydı içermelidir."},{status:400});
    const eventId=`GTW-${crypto.randomUUID()}`,payloadSha=await sha256(body);const insert=await env.DB.prepare("INSERT OR IGNORE INTO tracker_gateway_events (id,tenant_id,device_id,provider,protocol,external_message_id,payload_sha256,record_count,status) VALUES (?,?,?,?,?,?,?,?, 'RECEIVED')").bind(eventId,device.tenantId,device.deviceId,device.provider,device.protocol,messageId,payloadSha,records.length).run();if(!insert.meta.changes)return Response.json({duplicate:true,messageId,status:"ALREADY_RECEIVED"});
    const prepared:Array<{id:string;vehicleId:string;latitude:number;longitude:number;speed:number;battery:number;capturedAt:string;eventType:string;sequence:number;accuracy:number;altitude:number;heading:number}>=[];
    for(const [index,point] of records.entries()){
      const vehicleId=String(point.vehicleId||payload.vehicleId||"").trim().toLocaleUpperCase("tr-TR"),latitude=Number(point.latitude),longitude=Number(point.longitude),capturedAt=String(point.capturedAt||"");if(!vehicleId||vehicleId!==device.vehicleId||!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180||Number.isNaN(Date.parse(capturedAt))){await env.DB.prepare("UPDATE tracker_gateway_events SET status='REJECTED' WHERE id=?").bind(eventId).run();return Response.json({error:`${index+1}. gateway kaydı geçersiz veya atanmış araçla eşleşmiyor.`,messageId},{status:400})}const vehicle=await env.DB.prepare("SELECT id FROM module_records WHERE tenant_id=? AND module='fleet' AND archived=0 AND (id=? OR upper(json_extract(data,'$.plate'))=?)").bind(device.tenantId,vehicleId,vehicleId).first();if(!vehicle){await env.DB.prepare("UPDATE tracker_gateway_events SET status='REJECTED' WHERE id=?").bind(eventId).run();return Response.json({error:`${vehicleId} bu çalışma alanında aktif araç değil.`,messageId},{status:404})}prepared.push({id:`TEL-${crypto.randomUUID()}`,vehicleId,latitude,longitude,speed:Math.max(0,Math.round(Number(point.speed)||0)),battery:Math.min(100,Math.max(0,Math.round(Number(point.battery)||0))),capturedAt,eventType:String(point.eventType||"LOCATION").trim().toLocaleUpperCase("tr-TR"),sequence:Math.max(0,Math.round(Number(point.sequence)||index)),accuracy:Math.max(0,Math.round(Number(point.accuracy)||0)),altitude:Math.round(Number(point.altitude)||0),heading:Math.min(359,Math.max(0,Math.round(Number(point.heading)||0)))})
    }
    const statements=prepared.map(point=>env.DB.prepare("INSERT OR IGNORE INTO telemetry_events (id,tenant_id,vehicle_id,device_id,latitude,longitude,speed,battery,source,provider,event_type,sequence,accuracy,altitude,heading,session_id,captured_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'',?)").bind(point.id,device.tenantId,point.vehicleId,device.deviceId,String(point.latitude),String(point.longitude),point.speed,point.battery,device.provider,device.provider,point.eventType,point.sequence,point.accuracy,point.altitude,point.heading,point.capturedAt));const connectionProvider=device.provider==="TELTONIKA"?"TELTONIKA_GATEWAY":device.provider==="QUECLINK"?"QUECLINK_GATEWAY":"DEVICE_TELEMETRY";statements.push(env.DB.prepare("UPDATE tracker_gateway_events SET status='PROCESSED' WHERE id=?").bind(eventId),env.DB.prepare("UPDATE hardware_device_assignments SET status='ACTIVE',last_gateway_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND device_id=? AND imei=? AND status IN ('PROVISIONED','ACTIVE')").bind(device.tenantId,device.deviceId,device.imei),env.DB.prepare("UPDATE provider_connections SET status='CONNECTED',last_check_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND provider=?").bind(device.tenantId,connectionProvider),env.DB.prepare("INSERT INTO audit_events (id,tenant_id,actor_email,action,module,record_id,payload) VALUES (?,?,?,'TRACKER_GATEWAY_BATCH_ACCEPTED','trackers',?,?)").bind(`AUD-${crypto.randomUUID()}`,device.tenantId,`gateway:${device.provider}`,device.deviceId,JSON.stringify({messageId,protocol:device.protocol,modelCode:device.modelCode,imeiSuffix:device.imei.slice(-4),vehicleId:device.vehicleId,records:records.length,payloadSha})));await env.DB.batch(statements);return Response.json({ok:true,messageId,provider:device.provider,protocol:device.protocol,accepted:records.length},{status:201});
  }catch(error){return errorResponse(error)}
}
