import { assertPermission, requirePrivilegedAccess, requireWorkspace, runtimeEnv } from "../../../lib/platform-store";
import { assertRequestSize, assertSameOrigin, enforceRateLimit } from "../../../lib/security";
import { apiErrorResponse } from "../../../lib/api-errors";

export const dynamic="force-dynamic";
const MAX_BACKUP_SIZE=10*1024*1024;
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}

export async function POST(request:Request){const started=Date.now();try{
  assertSameOrigin(request);assertRequestSize(request,MAX_BACKUP_SIZE);const workspace=await requireWorkspace(false);assertPermission(workspace,"settings");await requirePrivilegedAccess(workspace,"restore-rehearsal");await enforceRateLimit(runtimeEnv().DB,request,"restore-rehearsal",4,600,workspace.email);
  const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_BACKUP_SIZE)return Response.json({error:"Yedek dosyası en fazla 10 MB olabilir."},{status:413});const backup=JSON.parse(raw) as Record<string,unknown>;if(backup.format!=="FILO_TENANT_EXPORT")return Response.json({error:"Geçersiz Filo yedek biçimi."},{status:400});const sourceWorkspace=backup.workspace as Record<string,unknown>|undefined;if(sourceWorkspace?.tenantId!==workspace.tenantId)return Response.json({error:"Yedek farklı bir çalışma alanına ait."},{status:409});
  const records=Array.isArray(backup.records)?backup.records as Array<Record<string,unknown>>:[],files=Array.isArray(backup.files)?backup.files as Array<Record<string,unknown>>:[],exportedAt=String(backup.exportedAt||"");if(!exportedAt||Number.isNaN(Date.parse(exportedAt)))return Response.json({error:"Yedek dışa aktarma zamanı geçersiz."},{status:400});
  const id=`RST-${crypto.randomUUID()}`,targetNamespace=`shadow:${workspace.tenantId}:${id}`,backupSha256=await sha256(raw),{DB}=runtimeEnv();await DB.prepare("INSERT INTO restore_rehearsals (id,tenant_id,backup_sha256,source_exported_at,status,target_namespace,created_by) VALUES (?,?,?,?,'RUNNING',?,?)").bind(id,workspace.tenantId,backupSha256,exportedAt,targetNamespace,workspace.email).run();
  const items=[...records.map(row=>({kind:"RECORD",key:`${String(row.module||"")}:${String(row.id||"")}`,row})),...files.map(row=>({kind:"FILE_METADATA",key:String(row.id||""),row}))];const seen=new Set<string>();for(const item of items){const unique=`${item.kind}:${item.key}`;if(!item.key||seen.has(unique))throw new Error(`Gölge geri yüklemede mükerrer/geçersiz anahtar: ${unique}`);seen.add(unique);await DB.prepare("INSERT INTO restore_staging_records (rehearsal_id,tenant_id,kind,source_key,payload_sha256) VALUES (?,?,?,?,?)").bind(id,workspace.tenantId,item.kind,item.key,await sha256(JSON.stringify(item.row))).run()}
  const staged=await DB.prepare("SELECT COUNT(*) AS count FROM restore_staging_records WHERE tenant_id=? AND rehearsal_id=?").bind(workspace.tenantId,id).first<{count:number}>(),rpoMinutes=Math.max(0,Math.floor((Date.now()-Date.parse(exportedAt))/60000)),rtoSeconds=Math.max(1,Math.ceil((Date.now()-started)/1000)),passed=Number(staged?.count||0)===items.length;
  await DB.batch([DB.prepare("UPDATE restore_rehearsals SET status=?,record_count=?,file_count=?,rpo_minutes=?,rto_seconds=? WHERE tenant_id=? AND id=?").bind(passed?"PASSED":"FAILED",records.length,files.length,rpoMinutes,rtoSeconds,workspace.tenantId,id),DB.prepare("INSERT INTO audit_events (id,tenant_id,actor_email,action,module,record_id,payload) VALUES (?,?,?,?,?,?,?)").bind(`AUD-${crypto.randomUUID()}`,workspace.tenantId,workspace.email,passed?"RESTORE_REHEARSAL_PASSED":"RESTORE_REHEARSAL_FAILED","security",id,JSON.stringify({backupSha256,targetNamespace,recordCount:records.length,fileCount:files.length,rpoMinutes,rtoSeconds,productionMutated:false}))]);
  return Response.json({passed,id,backupSha256,targetNamespace,recordCount:records.length,fileCount:files.length,rpoMinutes,rtoSeconds,productionMutated:false,scope:"ISOLATED_SHADOW_RESTORE"});
}catch(error){if(error instanceof Response)return error;if(error instanceof SyntaxError)return Response.json({error:"Yedek dosyası geçerli JSON değil."},{status:400});return apiErrorResponse(error,"Geri yükleme provası tamamlanamadı.")}}
