import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Application from "expo-application";
import * as Battery from "expo-battery";
import Constants from "expo-constants";
import * as Device from "expo-device";
import * as Location from "expo-location";
import * as Network from "expo-network";
import * as Notifications from "expo-notifications";
import * as SecureStore from "expo-secure-store";
import * as TaskManager from "expo-task-manager";
import { AppState, Platform } from "react-native";

export const LOCATION_TASK="FILO_DRIVER_BACKGROUND_LOCATION_V2";
const CONFIG_KEY="filo.driver.runtime.v2",QUEUE_KEY="filo.driver.outbox.v2",SEQUENCE_KEY="filo.driver.sequence.v2",MAX_QUEUE_ITEMS=10000;

export type DriverConfig={apiBaseUrl:string;token:string;deviceId:string;driverId:string;vehicleId:string;sessionId?:string;pendingStop?:boolean;expoProjectId?:string};
type QueuedPoint={vehicleId:string;sessionId:string;source:"MOBILE";eventType:"LOCATION";sequence:number;latitude:number;longitude:number;speed:number;battery:number;accuracy:number;altitude:number;heading:number;capturedAt:string};
type RuntimeEventType="APP_STATE"|"NETWORK_STATE"|"LOCATION_BATCH"|"QUEUE_ENQUEUED"|"QUEUE_FLUSH_STARTED"|"QUEUE_FLUSH_COMPLETED"|"BATTERY_SAMPLE"|"SHIFT_STARTED"|"SHIFT_STOPPED"|"RUNTIME_RECOVERED"|"TERMINATION_LIMIT_ACKNOWLEDGED"|"QUEUE_OVERFLOW";
type RuntimeDiagnostic={action:"diagnostic";eventId:string;sessionId:string;eventType:RuntimeEventType;sequence:number;occurredAt:string;batteryPercent:number;queueDepth:number;networkType:string;appState:string;details:Record<string,unknown>};
type OutboxItem={id:string;kind:"TELEMETRY";payload:QueuedPoint}|{id:string;kind:"DIAGNOSTIC";payload:RuntimeDiagnostic};

let queueMutex:Promise<void>=Promise.resolve(),flushPromise:Promise<number>|null=null;
function withQueueLock<T>(operation:()=>Promise<T>){const next=queueMutex.then(operation,operation);queueMutex=next.then(()=>undefined,()=>undefined);return next}
function eventId(){return `MEV-${Date.now()}-${Math.random().toString(36).slice(2,12)}`}
async function readConfig(){const value=await SecureStore.getItemAsync(CONFIG_KEY);return value?JSON.parse(value) as DriverConfig:null}
export async function restoreDriverConfig(){return readConfig()}
async function writeConfig(config:DriverConfig){await SecureStore.setItemAsync(CONFIG_KEY,JSON.stringify(config),{keychainAccessible:SecureStore.AFTER_FIRST_UNLOCK})}
async function readQueue(){return JSON.parse(await AsyncStorage.getItem(QUEUE_KEY)||"[]") as OutboxItem[]}
async function nextSequence(){return withQueueLock(async()=>{const previous=Math.max(0,Number(await AsyncStorage.getItem(SEQUENCE_KEY)||0)),next=Math.max(previous+1,Date.now()*1000);await AsyncStorage.setItem(SEQUENCE_KEY,String(next));return next})}
async function batterySnapshot(){const [level,state,lowPowerMode]=await Promise.all([Battery.getBatteryLevelAsync(),Battery.getBatteryStateAsync(),Battery.isLowPowerModeEnabledAsync()]);return {percent:level>=0?Math.round(level*100):-1,state:String(Battery.BatteryState[state]||state),lowPowerMode}}
async function networkSnapshot(){const state=await Network.getNetworkStateAsync();return {type:String(state.type||"UNKNOWN"),connected:state.isConnected===true,internetReachable:state.isInternetReachable===true}}
async function diagnostic(config:DriverConfig,eventType:RuntimeEventType,details:Record<string,unknown>={},queueDepth=0):Promise<RuntimeDiagnostic>{const [battery,network,sequence]=await Promise.all([batterySnapshot(),networkSnapshot(),nextSequence()]);return {action:"diagnostic",eventId:eventId(),sessionId:config.sessionId||"",eventType,sequence,occurredAt:new Date().toISOString(),batteryPercent:battery.percent,queueDepth,networkType:network.type,appState:AppState.currentState,details:{...details,batteryState:battery.state,lowPowerMode:battery.lowPowerMode,connected:network.connected,internetReachable:network.internetReachable}}}
async function send(config:DriverConfig,path:string,body:Record<string,unknown>){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(`${config.apiBaseUrl.replace(/\/$/,"")}${path}`,{method:"POST",headers:{Authorization:`Bearer ${config.token}`,"Content-Type":"application/json"},body:JSON.stringify(body),signal:controller.signal});const result=await response.json().catch(()=>({})) as {error?:string};if(!response.ok)throw new Error(result.error||`Sunucu ${response.status}`);return result}finally{clearTimeout(timeout)}}
async function sendItem(config:DriverConfig,item:OutboxItem){return item.kind==="TELEMETRY"?send(config,"/api/device-telemetry",item.payload):send(config,"/api/mobile-runtime",item.payload)}

async function appendOutbox(items:OutboxItem[],config:DriverConfig){return withQueueLock(async()=>{const current=await readQueue(),combined=[...current,...items];if(combined.length<=MAX_QUEUE_ITEMS){await AsyncStorage.setItem(QUEUE_KEY,JSON.stringify(combined));return combined.length}const dropped=combined.length-(MAX_QUEUE_ITEMS-1),overflowId=eventId(),overflow:RuntimeDiagnostic={action:"diagnostic",eventId:overflowId,sessionId:config.sessionId||"",eventType:"QUEUE_OVERFLOW",sequence:Date.now()*1000,occurredAt:new Date().toISOString(),batteryPercent:-1,queueDepth:MAX_QUEUE_ITEMS,networkType:"UNKNOWN",appState:AppState.currentState,details:{dropped}};const bounded=[...combined.slice(-(MAX_QUEUE_ITEMS-1)),{id:overflowId,kind:"DIAGNOSTIC" as const,payload:overflow}];await AsyncStorage.setItem(QUEUE_KEY,JSON.stringify(bounded));return bounded.length})}
async function queuePoint(config:DriverConfig,point:QueuedPoint){const depth=(await readQueue()).length+1,queued=await diagnostic(config,"QUEUE_ENQUEUED",{telemetrySequence:point.sequence,capturedAt:point.capturedAt},depth+1);return appendOutbox([{id:`TELQ-${point.sequence}`,kind:"TELEMETRY",payload:point},{id:queued.eventId,kind:"DIAGNOSTIC",payload:queued}],config)}

export async function flushQueue(){if(flushPromise)return flushPromise;flushPromise=(async()=>{const config=await readConfig();if(!config?.sessionId)return 0;const snapshot=await withQueueLock(readQueue);if(!snapshot.length)return 0;const started=await diagnostic(config,"QUEUE_FLUSH_STARTED",{pending:snapshot.length},snapshot.length);await send(config,"/api/mobile-runtime",started).catch(()=>undefined);let sent=0;for(const item of snapshot){try{await sendItem(config,item);sent++}catch{break}}if(sent>0)await withQueueLock(async()=>{const current=await readQueue(),sentIds=new Set(snapshot.slice(0,sent).map(item=>item.id));await AsyncStorage.setItem(QUEUE_KEY,JSON.stringify(current.filter(item=>!sentIds.has(item.id))))});const remaining=(await readQueue()).length;if(sent>0){const completed=await diagnostic(config,"QUEUE_FLUSH_COMPLETED",{sent,remaining},remaining);await send(config,"/api/mobile-runtime",completed).catch(()=>appendOutbox([{id:completed.eventId,kind:"DIAGNOSTIC",payload:completed}],config))}return sent})().finally(()=>{flushPromise=null});return flushPromise}

TaskManager.defineTask(LOCATION_TASK,async({data,error})=>{
  if(error||!data)return;const config=await readConfig();if(!config?.sessionId)return;const locations=(data as {locations:Location.LocationObject[]}).locations||[],battery=await batterySnapshot();
  for(const location of locations){const sequence=await nextSequence(),point:QueuedPoint={vehicleId:config.vehicleId,sessionId:config.sessionId,source:"MOBILE",eventType:"LOCATION",sequence,latitude:location.coords.latitude,longitude:location.coords.longitude,speed:Math.max(0,location.coords.speed||0)*3.6,battery:Math.max(0,battery.percent),accuracy:Math.round(location.coords.accuracy||0),altitude:Math.round(location.coords.altitude||0),heading:Math.round(location.coords.heading||0),capturedAt:new Date(location.timestamp).toISOString()};try{await send(config,"/api/device-telemetry",point)}catch{await queuePoint(config,point)}}
  const batch=await diagnostic(config,"LOCATION_BATCH",{count:locations.length,batteryState:battery.state,lowPowerMode:battery.lowPowerMode},(await readQueue()).length);await send(config,"/api/mobile-runtime",batch).catch(()=>appendOutbox([{id:batch.eventId,kind:"DIAGNOSTIC",payload:batch}],config));await flushQueue();
});

export async function registerDevice(config:DriverConfig){
  const foreground=await Location.requestForegroundPermissionsAsync();if(foreground.status!=="granted")throw new Error("Ön plan konum izni verilmedi.");const background=await Location.requestBackgroundPermissionsAsync();
  const notification=await Notifications.requestPermissionsAsync(),projectId=config.expoProjectId||Constants.expoConfig?.extra?.eas?.projectId;let pushToken="";if(notification.status==="granted"&&projectId)pushToken=(await Notifications.getExpoPushTokenAsync({projectId})).data;
  const payload={action:"register",platform:Platform.OS==="ios"?"IOS":"ANDROID",osVersion:String(Platform.Version),appVersion:Application.nativeApplicationVersion||"1.28.20",deviceModel:Device.modelName||"UNKNOWN",driverId:config.driverId,foregroundPermission:foreground.status==="granted"?"GRANTED":"DENIED",backgroundPermission:background.status==="granted"?(Platform.OS==="ios"?"ALWAYS":"GRANTED"):"DENIED",foregroundService:Platform.OS==="android"?"ACTIVE":"NOT_APPLICABLE",batteryOptimization:"REQUIRES_OEM_CHECK",notificationPermission:notification.status==="granted"?"GRANTED":"DENIED",pushToken};await send(config,"/api/mobile-runtime",payload);await writeConfig(config);return payload;
}

export async function startShift(config:DriverConfig){const result=await send(config,"/api/mobile-runtime",{action:"start-session",vehicleId:config.vehicleId}) as {session?:{id:string}};if(!result.session?.id)throw new Error("Takip oturumu oluşturulamadı.");const next={...config,sessionId:result.session.id,pendingStop:false};await writeConfig(next);try{await Location.startLocationUpdatesAsync(LOCATION_TASK,{accuracy:Location.Accuracy.High,distanceInterval:25,timeInterval:30000,deferredUpdatesDistance:100,deferredUpdatesInterval:60000,showsBackgroundLocationIndicator:true,foregroundService:{notificationTitle:"Filo vardiyası aktif",notificationBody:"Konum yalnız aktif vardiya süresince işleniyor.",killServiceOnDestroy:false}});await recordRuntimeState("SHIFT_STARTED",{locationTask:LOCATION_TASK});return next}catch(error){const stopped=await send(next,"/api/mobile-runtime",{action:"stop-session",sessionId:next.sessionId}).then(()=>true).catch(()=>false);await writeConfig(stopped?{...next,sessionId:undefined,pendingStop:false}:{...next,pendingStop:true});throw error}}
export async function stopShift(){const config=await readConfig();if(!config?.sessionId)return {pending:false};await recordRuntimeState("SHIFT_STOPPED");await Location.stopLocationUpdatesAsync(LOCATION_TASK);await flushQueue();if((await readQueue()).length){await writeConfig({...config,pendingStop:true});return {pending:true}}try{await send(config,"/api/mobile-runtime",{action:"stop-session",sessionId:config.sessionId});await writeConfig({...config,sessionId:undefined,pendingStop:false});return {pending:false}}catch{await writeConfig({...config,pendingStop:true});return {pending:true}}}
export async function heartbeat(){const config=await readConfig();if(!config?.sessionId)return null;await flushQueue();if(config.pendingStop&&(await readQueue()).length===0){const result=await send(config,"/api/mobile-runtime",{action:"stop-session",sessionId:config.sessionId});await writeConfig({...config,sessionId:undefined,pendingStop:false});return result}return send(config,"/api/mobile-runtime",{action:"heartbeat",sessionId:config.sessionId})}
export async function recordRuntimeState(eventType:RuntimeEventType,details:Record<string,unknown>={}){const config=await readConfig();if(!config?.sessionId)return null;const event=await diagnostic(config,eventType,details,(await readQueue()).length);try{return await send(config,"/api/mobile-runtime",event)}catch{await appendOutbox([{id:event.eventId,kind:"DIAGNOSTIC",payload:event}],config);return null}}
export async function runtimeDiagnostics(){const [config,queue,battery,network,taskActive]=await Promise.all([readConfig(),readQueue(),batterySnapshot(),networkSnapshot(),Location.hasStartedLocationUpdatesAsync(LOCATION_TASK)]);return {sessionId:config?.sessionId||"",pendingStop:config?.pendingStop===true,queueDepth:queue.length,oldestQueuedAt:queue[0]?.kind==="TELEMETRY"?queue[0].payload.capturedAt:queue[0]?.payload.occurredAt||null,batteryPercent:battery.percent,batteryState:battery.state,lowPowerMode:battery.lowPowerMode,networkType:network.type,connected:network.connected,taskActive}}
