import { useEffect, useState } from "react";
import { AppState, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { DriverConfig, heartbeat, recordRuntimeState, registerDevice, restoreDriverConfig, runtimeDiagnostics, startShift, stopShift } from "./src/driver-runtime";

type Diagnostics=Awaited<ReturnType<typeof runtimeDiagnostics>>;
export default function App(){
  const [config,setConfig]=useState<DriverConfig>({apiBaseUrl:"https://filo-platform-prototip.aydinalt.chatgpt.site",token:"",deviceId:"",driverId:"",vehicleId:""}),[registered,setRegistered]=useState(false),[active,setActive]=useState(false),[message,setMessage]=useState("Kurulum profili bekleniyor."),[diagnostics,setDiagnostics]=useState<Diagnostics>();
  useEffect(()=>{const refresh=async()=>{const [value,saved]=await Promise.all([runtimeDiagnostics(),restoreDriverConfig()]);setDiagnostics(value);if(saved?.token){setConfig(saved);setRegistered(true)}if(value.sessionId){setActive(!value.pendingStop);void recordRuntimeState("RUNTIME_RECOVERED",{locationTaskActive:value.taskActive,pendingStop:value.pendingStop});if(value.pendingStop)void heartbeat().catch(()=>undefined)}};void refresh().catch(()=>undefined);const timer=setInterval(()=>{void runtimeDiagnostics().then(setDiagnostics).catch(()=>undefined);void heartbeat().catch(()=>undefined)},30000),subscription=AppState.addEventListener("change",state=>{void recordRuntimeState("APP_STATE",{state});void runtimeDiagnostics().then(setDiagnostics).catch(()=>undefined)});return()=>{clearInterval(timer);subscription.remove()}},[]);
  const run=async(action:"register"|"start"|"stop")=>{try{if(action==="register"){await registerDevice(config);setRegistered(true);setMessage("Telefon ve izinler sunucuda doğrulandı.")}if(action==="start"){const next=await startShift(config);setConfig(next);setActive(true);setMessage("Vardiya ve arka plan konumu aktif.")}if(action==="stop"){const result=await stopShift();setActive(false);setMessage(result?.pending?"Konum durdu; çevrimdışı kuyruk gönderilince oturum kapatılacak.":"Vardiya kapatıldı; kuyruk eşitlendi.")}setDiagnostics(await runtimeDiagnostics())}catch(error){setMessage(error instanceof Error?error.message:"İşlem başarısız.")}};
  return <SafeAreaView style={styles.safe}><View style={styles.card}><Text style={styles.eyebrow}>FİLO SÜRÜCÜ · 1.28.20</Text><Text style={styles.title}>{active?"Vardiya aktif":"Cihaz kurulumu"}</Text><Text style={styles.message}>{message}</Text>{!registered&&<>{(["apiBaseUrl","token","deviceId","driverId","vehicleId"] as const).map(key=><TextInput key={key} style={styles.input} secureTextEntry={key==="token"} autoCapitalize={key==="apiBaseUrl"||key==="token"?"none":"characters"} placeholder={key} value={config[key]} onChangeText={value=>setConfig({...config,[key]:value})}/>)}</>}<TouchableOpacity style={styles.primary} onPress={()=>run(!registered?"register":active?"stop":"start")}><Text style={styles.primaryText}>{!registered?"Telefonu doğrula":active?"Vardiyayı bitir":"Vardiyayı başlat"}</Text></TouchableOpacity>{diagnostics&&<View style={styles.health}><Text style={styles.healthTitle}>SAHA TANILAMA</Text><Text style={styles.healthText}>Konum görevi: {diagnostics.taskActive?"AKTİF":"DURDU"} · Kuyruk: {diagnostics.queueDepth}</Text><Text style={styles.healthText}>Pil: %{diagnostics.batteryPercent} · Ağ: {diagnostics.networkType} / {diagnostics.connected?"BAĞLI":"ÇEVRİMDIŞI"}</Text></View>}<Text style={styles.notice}>Konum yalnız aktif vardiyada, yayımlanmış amaç ve tebliğ edilmiş bildirim kapsamında işlenir. Uygulamayı zorla kapatmak iOS/Android tarafından kesintisiz takip garantisi vermez.</Text></View></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#f3f4f6",justifyContent:"center",padding:20},card:{backgroundColor:"white",borderWidth:1,borderColor:"#dfe3e8",borderRadius:18,padding:22},eyebrow:{fontSize:11,fontWeight:"700",color:"#2563eb",letterSpacing:1.1},title:{fontSize:28,fontWeight:"700",color:"#18181b",marginTop:8},message:{fontSize:14,color:"#64748b",lineHeight:20,marginVertical:16},input:{height:48,borderWidth:1,borderColor:"#dfe3e8",borderRadius:10,paddingHorizontal:13,marginBottom:10,color:"#18181b"},primary:{height:50,borderRadius:10,backgroundColor:"#18181b",alignItems:"center",justifyContent:"center",marginTop:6},primaryText:{color:"white",fontWeight:"700"},health:{backgroundColor:"#eff6ff",borderRadius:10,padding:12,marginTop:14},healthTitle:{fontSize:10,fontWeight:"800",color:"#2563eb",letterSpacing:1},healthText:{fontSize:12,color:"#334155",marginTop:4},notice:{fontSize:11,color:"#64748b",lineHeight:17,marginTop:16}});
