import type {FastifyInstance} from "fastify";
import {actionQuerySchema,createActionItemSchema,updateActionItemSchema} from "@filo/contracts";
import {withTenantTransaction} from "@filo/database";
import {requireSession} from "../lib/auth.js"; import {allow} from "../lib/permissions.js";
const selectAction=`SELECT a.id,a.source_type AS "sourceType",a.source_id AS "sourceId",a.title,a.description,a.priority,a.status,a.vehicle_id AS "vehicleId",v.plate AS "vehiclePlate",a.assigned_user_id AS "assignedUserId",u.full_name AS "assignedUserName",a.due_on AS "dueOn",a.completed_at AS "completedAt",a.created_at AS "createdAt" FROM action_items a LEFT JOIN vehicles v ON v.id=a.vehicle_id LEFT JOIN users u ON u.id=a.assigned_user_id`;
const shape=(r:any)=>({...r,dueOn:r.dueOn?.toISOString().slice(0,10)??null,completedAt:r.completedAt?.toISOString()??null,createdAt:r.createdAt.toISOString()});
export async function actionRoutes(app:FastifyInstance){
 app.post("/generate",{preHandler:[requireSession,allow("owner","admin","operator")]},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>{
  const tenant=request.sessionUser.tenantId,user=request.sessionUser.id;
  const sources=[`SELECT 'maintenance',p.id,'Geciken bakım: '||p.title,'high',p.vehicle_id,p.due_date FROM vehicle_maintenance_plans p WHERE p.status='scheduled' AND p.due_date<CURRENT_DATE`,`SELECT 'document',d.id,'Süresi dolan araç belgesi','high',d.vehicle_id,d.expires_on FROM vehicle_documents d WHERE d.status='active' AND d.expires_on<CURRENT_DATE`,`SELECT 'defect',d.id,'Açık araç kusuru: '||d.item,CASE WHEN d.severity='critical' THEN 'critical' ELSE 'high' END,i.vehicle_id,CURRENT_DATE FROM inspection_defects d JOIN vehicle_inspections i ON i.id=d.inspection_id WHERE d.status<>'resolved'`,`SELECT 'safety_event',s.id,'Sürücü güvenlik olayı: '||s.event_type,CASE WHEN s.severity='critical' THEN 'critical' ELSE 'high' END,a.vehicle_id,CURRENT_DATE FROM driver_safety_events s JOIN vehicle_assignments a ON a.id=s.assignment_id WHERE s.status<>'resolved' AND s.severity IN ('high','critical')`,`SELECT 'incident',i.id,'Açık olay dosyası: '||i.incident_type,CASE WHEN i.severity='critical' THEN 'critical' ELSE 'high' END,i.vehicle_id,CURRENT_DATE FROM vehicle_incidents i WHERE i.status IN ('open','reviewing')`];
  let created=0;for(const source of sources){const result=await c.query(`INSERT INTO action_items(tenant_id,source_type,source_id,title,priority,vehicle_id,due_on,created_by) SELECT $1,x.*,$2 FROM (${source}) x ON CONFLICT(tenant_id,source_type,source_id) DO NOTHING`,[tenant,user]);created+=result.rowCount??0;}
  await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'actions.generated','action_center',$2,jsonb_build_object('created',$3))`,[tenant,user,created]);return{created};
 }));
 app.get("/",{preHandler:requireSession},async(request,reply)=>{const parsed=actionQuerySchema.safeParse(request.query);if(!parsed.success)return reply.code(400).send({error:"INVALID_ACTION_QUERY"});return withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>{const params:any[]=[];let where="";if(parsed.data.status){params.push(parsed.data.status);where=" WHERE a.status=$1";}const rows=(await c.query(`${selectAction}${where} ORDER BY CASE a.priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,a.due_on NULLS LAST,a.created_at DESC`,params)).rows;return{actions:rows.map(shape)};});});
 app.post("/",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const parsed=createActionItemSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_ACTION"});const user=request.sessionUser;const row=await withTenantTransaction(user.tenantId,user.id,async c=>{if(parsed.data.assignedUserId){const m=await c.query("SELECT 1 FROM memberships WHERE tenant_id=$1 AND user_id=$2",[user.tenantId,parsed.data.assignedUserId]);if(!m.rowCount)return null;}const result=await c.query(`INSERT INTO action_items(tenant_id,source_type,title,description,priority,vehicle_id,assigned_user_id,due_on,created_by) VALUES($1,'manual',$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[user.tenantId,parsed.data.title,parsed.data.description,parsed.data.priority,parsed.data.vehicleId,parsed.data.assignedUserId,parsed.data.dueOn,user.id]);await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'action.created','action_item',$3,'{}')`,[user.tenantId,user.id,result.rows[0].id]);return(await c.query(`${selectAction} WHERE a.id=$1`,[result.rows[0].id])).rows[0];});return row?reply.code(201).send({action:shape(row)}):reply.code(400).send({error:"ASSIGNEE_NOT_IN_TENANT"});});
 app.patch("/:id",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const id=(request.params as any).id,parsed=updateActionItemSchema.safeParse(request.body);if(!id||!parsed.success)return reply.code(400).send({error:"INVALID_ACTION_UPDATE"});const user=request.sessionUser;const changed=await withTenantTransaction(user.tenantId,user.id,async c=>{if(parsed.data.assignedUserId){const m=await c.query("SELECT 1 FROM memberships WHERE tenant_id=$1 AND user_id=$2",[user.tenantId,parsed.data.assignedUserId]);if(!m.rowCount)return false;}const r=await c.query(`UPDATE action_items SET status=$2,assigned_user_id=$3,due_on=$4,completed_at=CASE WHEN $2='completed' THEN now() ELSE NULL END,completed_by=CASE WHEN $2='completed' THEN $5 ELSE NULL END,updated_at=now() WHERE id=$1 RETURNING id`,[id,parsed.data.status,parsed.data.assignedUserId,parsed.data.dueOn,user.id]);if(!r.rowCount)return false;await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'action.updated','action_item',$3,jsonb_build_object('status',$4))`,[user.tenantId,user.id,id,parsed.data.status]);return true;});return changed?reply.code(204).send():reply.code(404).send({error:"ACTION_OR_ASSIGNEE_NOT_FOUND"});});
}
