import type {FastifyInstance} from "fastify";
import {deliveryQuerySchema,updateDeliveryStatusSchema,updateNotificationPreferencesSchema} from "@filo/contracts";
import {withTenantTransaction} from "@filo/database";
import {requireSession} from "../lib/auth.js";
import {allow} from "../lib/permissions.js";
import {renderTemplate} from "../lib/template-renderer.js";

const preferencesSelect=`SELECT email_enabled AS "emailEnabled",push_enabled AS "pushEnabled",quiet_hours_enabled AS "quietHoursEnabled",to_char(quiet_start,'HH24:MI') AS "quietStart",to_char(quiet_end,'HH24:MI') AS "quietEnd",timezone,updated_at AS "updatedAt" FROM notification_preferences WHERE user_id=$1`;
const deliverySelect=`SELECT o.id,o.notification_id AS "notificationId",n.title,o.recipient_user_id AS "recipientUserId",u.full_name AS "recipientName",o.channel,o.status,o.attempt_count AS "attemptCount",o.available_at AS "availableAt",o.delivered_at AS "deliveredAt",o.last_error AS "lastError",o.created_at AS "createdAt" FROM notification_delivery_outbox o JOIN in_app_notifications n ON n.id=o.notification_id JOIN users u ON u.id=o.recipient_user_id`;
const shape=(row:any)=>({...row,updatedAt:row.updatedAt?.toISOString()??null,availableAt:row.availableAt?.toISOString(),deliveredAt:row.deliveredAt?.toISOString()??null,createdAt:row.createdAt?.toISOString()});

export async function deliveryRoutes(app:FastifyInstance){
 app.get("/preferences",{preHandler:requireSession},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>{const row=(await c.query(preferencesSelect,[request.sessionUser.id])).rows[0];return{preferences:row?shape(row):{emailEnabled:true,pushEnabled:true,quietHoursEnabled:false,quietStart:null,quietEnd:null,timezone:"Europe/Istanbul",updatedAt:null}};}));
 app.put("/preferences",{preHandler:requireSession},async(request,reply)=>{const parsed=updateNotificationPreferencesSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_NOTIFICATION_PREFERENCES"});const user=request.sessionUser;return withTenantTransaction(user.tenantId,user.id,async c=>{const p=parsed.data;await c.query(`INSERT INTO notification_preferences(tenant_id,user_id,email_enabled,push_enabled,quiet_hours_enabled,quiet_start,quiet_end,timezone) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(tenant_id,user_id) DO UPDATE SET email_enabled=$3,push_enabled=$4,quiet_hours_enabled=$5,quiet_start=$6,quiet_end=$7,timezone=$8,updated_at=now()`,[user.tenantId,user.id,p.emailEnabled,p.pushEnabled,p.quietHoursEnabled,p.quietStart,p.quietEnd,p.timezone]);await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'notification_preferences.updated','user',$2,'{}')`,[user.tenantId,user.id]);return reply.code(204).send();});});
 app.post("/enqueue",{preHandler:[requireSession,allow("owner","admin","operator")]},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>{
  const candidates=(await c.query(`SELECT n.id,n.tenant_id AS "tenantId",n.recipient_user_id AS "recipientUserId",n.source_type AS "sourceType",n.title,n.message,u.full_name AS "recipientName",p.timezone,p.quiet_hours_enabled AS "quietEnabled",p.quiet_start AS "quietStart",p.quiet_end AS "quietEnd",x.channel FROM in_app_notifications n JOIN users u ON u.id=n.recipient_user_id JOIN notification_preferences p ON p.tenant_id=n.tenant_id AND p.user_id=n.recipient_user_id CROSS JOIN LATERAL (VALUES('email',p.email_enabled),('push',p.push_enabled)) x(channel,enabled) WHERE x.enabled AND n.archived_at IS NULL AND n.source_type NOT IN ('provider_incident','archive_reconciliation') AND n.created_at>=now()-interval '30 days' AND NOT EXISTS(SELECT 1 FROM notification_delivery_outbox o WHERE o.notification_id=n.id AND o.recipient_user_id=n.recipient_user_id AND o.channel=x.channel)`)).rows;
  let created=0;
  for(const item of candidates){
   const locale="tr-TR",key=`notification.${item.sourceType}`;
   const template=(await c.query(`SELECT id,subject_template AS "subjectTemplate",body_template AS "bodyTemplate" FROM notification_templates WHERE key=$1 AND channel=$2 AND status='active' AND locale IN ($3,'tr-TR') ORDER BY (locale=$3) DESC LIMIT 1`,[key,item.channel,locale])).rows[0];
   const variables={title:item.title,message:item.message,recipientName:item.recipientName};
   const subject=template?renderTemplate(template.subjectTemplate,variables):item.title;
   const body=template?renderTemplate(template.bodyTemplate,variables):item.message;
   const result=await c.query(`INSERT INTO notification_delivery_outbox(tenant_id,notification_id,recipient_user_id,channel,available_at,template_id,locale,rendered_subject,rendered_body) VALUES($1,$2,$3,$4,CASE WHEN $5 AND LOCALTIME>=$6 AND LOCALTIME<$7 THEN CURRENT_DATE+$7+interval '1 day' ELSE now() END,$8,$9,$10,$11) ON CONFLICT DO NOTHING`,[item.tenantId,item.id,item.recipientUserId,item.channel,item.quietEnabled,item.quietStart,item.quietEnd,template?.id??null,locale,subject,body]);
   created+=result.rowCount??0;
  }
  await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'notification_deliveries.enqueued','notification_delivery',$2,jsonb_build_object('created',$3))`,[request.sessionUser.tenantId,request.sessionUser.id,created]);return{created};
 }));
 app.get("/",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const parsed=deliveryQuerySchema.safeParse(request.query);if(!parsed.success)return reply.code(400).send({error:"INVALID_DELIVERY_QUERY"});return withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>{const params:any[]=[];const where=parsed.data.status==="all"?"":` WHERE o.status=$1`;if(where)params.push(parsed.data.status);return{deliveries:(await c.query(`${deliverySelect}${where} ORDER BY o.created_at DESC LIMIT 500`,params)).rows.map(shape)};});});
 app.get("/metrics",{preHandler:[requireSession,allow("owner","admin","operator")]},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>{const row=(await c.query(`SELECT count(*) FILTER(WHERE status='pending')::int AS pending,count(*) FILTER(WHERE status='processing')::int AS processing,count(*) FILTER(WHERE status='delivered')::int AS delivered,count(*) FILTER(WHERE status='failed')::int AS failed,count(*) FILTER(WHERE status='cancelled')::int AS cancelled,count(*) FILTER(WHERE status IN ('pending','failed') AND available_at<=now())::int AS ready,min(available_at) FILTER(WHERE status IN ('pending','failed') AND available_at<=now()) AS "oldestReadyAt" FROM notification_delivery_outbox`)).rows[0];return{metrics:{...row,oldestReadyAt:row.oldestReadyAt?.toISOString()??null}};}));
 app.patch("/:id",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const id=(request.params as any).id,parsed=updateDeliveryStatusSchema.safeParse(request.body);if(!id||!parsed.success)return reply.code(400).send({error:"INVALID_DELIVERY_UPDATE"});const user=request.sessionUser;const changed=await withTenantTransaction(user.tenantId,user.id,async c=>(await c.query(`UPDATE notification_delivery_outbox SET status=$2,attempt_count=attempt_count+1,last_error=$3,delivered_at=CASE WHEN $2='delivered' THEN now() ELSE NULL END,available_at=CASE WHEN $2='failed' THEN now()+LEAST(interval '1 hour',interval '1 minute'*power(2,attempt_count)) ELSE available_at END,updated_at=now() WHERE id=$1 AND status IN ('pending','processing','failed') AND attempt_count<10`,[id,parsed.data.status,parsed.data.error])).rowCount);return changed?reply.code(204).send():reply.code(404).send({error:"DELIVERY_NOT_FOUND_OR_FINAL"});});
}
