import type {FastifyInstance} from "fastify";
import {claimDeliveriesSchema,completeDeliverySchema} from "@filo/contracts";
import {withTenantTransaction} from "@filo/database";
import {requireNotificationWorker,retryDelayMinutes} from "../lib/worker-auth.js";

const workerGuard={preHandler:requireNotificationWorker};
export async function deliveryWorkerRoutes(app:FastifyInstance){
 app.post("/claim",workerGuard,async(request,reply)=>{const parsed=claimDeliveriesSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_CLAIM_REQUEST"});const p=parsed.data;return withTenantTransaction(p.tenantId,p.actorUserId,async c=>{await c.query(`UPDATE notification_delivery_outbox o SET status='cancelled',last_error='RECIPIENT_SUPPRESSED',updated_at=now() WHERE o.status IN ('pending','failed') AND EXISTS(SELECT 1 FROM notification_suppressions s WHERE s.recipient_user_id=o.recipient_user_id AND s.channel=o.channel AND s.active)`);const rows=(await c.query(`WITH candidates AS (SELECT o.id,pr.id AS provider_id,pr.provider FROM notification_delivery_outbox o JOIN notification_provider_profiles pr ON pr.tenant_id=o.tenant_id AND pr.channel=o.channel AND pr.status='active' WHERE o.status IN ('pending','failed') AND o.available_at<=now() AND o.attempt_count<10 AND o.rendered_body IS NOT NULL AND NOT EXISTS(SELECT 1 FROM notification_suppressions s WHERE s.recipient_user_id=o.recipient_user_id AND s.channel=o.channel AND s.active) AND (o.lease_expires_at IS NULL OR o.lease_expires_at<now()) ORDER BY o.available_at,o.id FOR UPDATE OF o SKIP LOCKED LIMIT $1) UPDATE notification_delivery_outbox o SET status='processing',locked_at=now(),locked_by=$2,lease_token=gen_random_uuid(),lease_expires_at=now()+interval '5 minutes',attempt_count=attempt_count+1,provider_profile_id=c.provider_id,updated_at=now() FROM candidates c,users u WHERE o.id=c.id AND u.id=o.recipient_user_id RETURNING o.id,o.lease_token AS "leaseToken",o.notification_id AS "notificationId",o.recipient_user_id AS "recipientUserId",u.email AS "recipientEmail",o.channel,c.provider,o.rendered_subject AS title,o.rendered_body AS message,o.locale,o.attempt_count AS "attemptCount",o.lease_expires_at AS "leaseExpiresAt"`,[p.limit,p.workerId])).rows;return{deliveries:rows.map((r:any)=>({...r,leaseExpiresAt:r.leaseExpiresAt.toISOString()}))};});});
 app.post("/:id/complete",workerGuard,async(request,reply)=>{const id=(request.params as any).id,parsed=completeDeliverySchema.safeParse(request.body);if(!id||!parsed.success)return reply.code(400).send({error:"INVALID_COMPLETION_REQUEST"});const p=parsed.data;return withTenantTransaction(p.tenantId,p.actorUserId,async c=>{const current=(await c.query(`SELECT attempt_count FROM notification_delivery_outbox WHERE id=$1 AND lease_token=$2 AND status='processing' AND lease_expires_at>now() FOR UPDATE`,[id,p.leaseToken])).rows[0];if(!current)return reply.code(409).send({error:"DELIVERY_LEASE_INVALID_OR_EXPIRED"});const next=p.outcome==="delivered"?"delivered":current.attempt_count>=10?"cancelled":"failed",delay=retryDelayMinutes(current.attempt_count);await c.query(`UPDATE notification_delivery_outbox SET status=$2,delivered_at=CASE WHEN $2='delivered' THEN now() ELSE NULL END,last_error=$3,available_at=CASE WHEN $2='failed' THEN now()+($4||' minutes')::interval ELSE available_at END,lease_token=NULL,lease_expires_at=NULL,locked_at=NULL,locked_by=NULL,updated_at=now() WHERE id=$1`,[id,next,p.error,delay]);await c.query(`INSERT INTO notification_delivery_attempts(tenant_id,delivery_id,outcome,provider_message_id,error) VALUES($1,$2,$3,$4,$5)`,[p.tenantId,id,p.outcome,p.providerMessageId,p.error]);return reply.code(204).send();});});
 app.get("/health",workerGuard,async()=>({status:"ok",adapter:"dry-run",providerConfigured:false}));
}
