import type { FastifyInstance } from "fastify";
import { createVehicleIncidentSchema, updateVehicleIncidentSchema } from "@filo/contracts";
import { withTenantTransaction } from "@filo/database";
import { requireSession } from "../lib/auth.js";
import { allow } from "../lib/permissions.js";

const selectIncidents=`SELECT i.id,i.vehicle_id AS "vehicleId",v.plate AS "vehiclePlate",i.driver_id AS "driverId",d.full_name AS "driverName",i.incident_type AS "incidentType",i.severity,i.occurred_at AS "occurredAt",i.location,i.description,i.injury_reported AS "injuryReported",i.police_report_number AS "policeReportNumber",i.insurance_claim_number AS "insuranceClaimNumber",i.estimated_cost AS "estimatedCost",i.actual_cost AS "actualCost",i.status,i.resolution_notes AS "resolutionNotes",i.resolved_at AS "resolvedAt",i.created_at AS "createdAt" FROM vehicle_incidents i JOIN vehicles v ON v.id=i.vehicle_id LEFT JOIN drivers d ON d.id=i.driver_id`;
const mapIncident=(r:Record<string,any>):Record<string,any>=>({...r,occurredAt:r.occurredAt.toISOString(),estimatedCost:r.estimatedCost===null?null:Number(r.estimatedCost),actualCost:r.actualCost===null?null:Number(r.actualCost),resolvedAt:r.resolvedAt?.toISOString()??null,createdAt:r.createdAt.toISOString()});

export async function incidentRoutes(app:FastifyInstance){
  app.get("/",{preHandler:[requireSession]},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>{const rows=(await c.query(`${selectIncidents} ORDER BY i.occurred_at DESC LIMIT 500`)).rows.map(mapIncident);return {incidents:rows,summary:{total:rows.length,open:rows.filter(x=>x.status==='open'||x.status==='reviewing').length,critical:rows.filter(x=>x.severity==='critical'&&(x.status==='open'||x.status==='reviewing')).length,estimatedExposure:rows.filter(x=>x.status==='open'||x.status==='reviewing').reduce((sum,x)=>sum+(x.estimatedCost??0),0)}};}));
  app.post("/",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const parsed=createVehicleIncidentSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_INCIDENT"});if(new Date(parsed.data.occurredAt).getTime()>Date.now()+300000)return reply.code(400).send({error:"FUTURE_INCIDENT"});const u=request.sessionUser;const incident=await withTenantTransaction(u.tenantId,u.id,async c=>{const related=await c.query(`SELECT v.id FROM vehicles v LEFT JOIN drivers d ON d.id=$2 WHERE v.id=$1 AND ($2::uuid IS NULL OR d.id IS NOT NULL)`,[parsed.data.vehicleId,parsed.data.driverId]);if(!related.rowCount)return null;const r=(await c.query(`INSERT INTO vehicle_incidents(tenant_id,vehicle_id,driver_id,incident_type,severity,occurred_at,location,description,injury_reported,police_report_number,insurance_claim_number,estimated_cost,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id`,[u.tenantId,parsed.data.vehicleId,parsed.data.driverId,parsed.data.incidentType,parsed.data.severity,parsed.data.occurredAt,parsed.data.location,parsed.data.description,parsed.data.injuryReported,parsed.data.policeReportNumber,parsed.data.insuranceClaimNumber,parsed.data.estimatedCost,u.id])).rows[0];await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'vehicle_incident.created','vehicle_incident',$3,jsonb_build_object('vehicleId',$4,'severity',$5))`,[u.tenantId,u.id,r.id,parsed.data.vehicleId,parsed.data.severity]);return mapIncident((await c.query(`${selectIncidents} WHERE i.id=$1`,[r.id])).rows[0]);});return incident?reply.code(201).send({incident}):reply.code(404).send({error:"VEHICLE_OR_DRIVER_NOT_FOUND"});});
  app.patch("/:id",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const {id}=request.params as {id:string};const parsed=updateVehicleIncidentSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_INCIDENT_UPDATE"});const u=request.sessionUser;const ok=await withTenantTransaction(u.tenantId,u.id,async c=>{const r=await c.query(`UPDATE vehicle_incidents SET status=$2,resolution_notes=$3,insurance_claim_number=COALESCE($4,insurance_claim_number),actual_cost=$5,resolved_at=CASE WHEN $2 IN ('resolved','closed') THEN now() ELSE NULL END,updated_at=now() WHERE id=$1 AND status<>'closed' RETURNING id`,[id,parsed.data.status,parsed.data.resolutionNotes,parsed.data.insuranceClaimNumber,parsed.data.actualCost]);if(!r.rowCount)return false;await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'vehicle_incident.status_changed','vehicle_incident',$3,jsonb_build_object('status',$4))`,[u.tenantId,u.id,id,parsed.data.status]);return true;});return ok?reply.code(204).send():reply.code(404).send({error:"OPEN_INCIDENT_NOT_FOUND"});});
}
