import type {FastifyInstance} from "fastify";
import {randomUUID} from "node:crypto";
import {createNotificationRuleSchema,manualReconcileNotificationArchiveSchema,notificationQuerySchema,retryNotificationArchiveSchema,updateNotificationRetentionSchema,updateNotificationRuleSchema} from "@filo/contracts";
import {withTenantTransaction} from "@filo/database";
import {requireSession} from "../lib/auth.js";
import {allow} from "../lib/permissions.js";
import {countEligibleNotifications,executeNotificationArchiveAttempt,loadNotificationRetentionState,reconcileStaleNotificationArchiveAttempts} from "../lib/notification-retention.js";

const ruleSelect=`SELECT id,name,source_type AS "sourceType",lead_days AS "leadDays",severity,target_role AS "targetRole",status,created_at AS "createdAt" FROM notification_rules`;
const notificationSelect=`SELECT n.id,n.rule_id AS "ruleId",n.source_type AS "sourceType",n.source_id AS "sourceId",n.title,n.message,n.severity,n.vehicle_id AS "vehicleId",v.plate AS "vehiclePlate",n.recipient_user_id AS "recipientUserId",n.action_target_type AS "actionTargetType",n.action_target_id AS "actionTargetId",n.read_at AS "readAt",n.archived_at AS "archivedAt",n.created_at AS "createdAt" FROM in_app_notifications n LEFT JOIN vehicles v ON v.id=n.vehicle_id`;
const shapeRule=(row:any)=>({...row,createdAt:row.createdAt.toISOString()});
const shapeNotification=(row:any)=>{const{actionTargetType,actionTargetId,...item}=row;return{...item,actionTarget:actionTargetType&&actionTargetId?{type:actionTargetType,id:actionTargetId}:null,readAt:row.readAt?.toISOString()??null,archivedAt:row.archivedAt?.toISOString()??null,createdAt:row.createdAt.toISOString()};};
const shapeArchiveRun=(row:any)=>({...row,cutoffAt:row.cutoffAt.toISOString(),createdAt:row.createdAt.toISOString()});
const shapeReconciliation=(row:any)=>({...row,createdAt:row.createdAt.toISOString()});

export async function notificationRoutes(app:FastifyInstance){
 app.get("/rules",{preHandler:requireSession},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>({rules:(await c.query(`${ruleSelect} ORDER BY created_at DESC`)).rows.map(shapeRule)})));
 app.post("/rules",{preHandler:[requireSession,allow("owner","admin")]},async(request,reply)=>{const parsed=createNotificationRuleSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_NOTIFICATION_RULE"});const user=request.sessionUser;return withTenantTransaction(user.tenantId,user.id,async c=>{const result=await c.query(`INSERT INTO notification_rules(tenant_id,name,source_type,lead_days,severity,target_role,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[user.tenantId,parsed.data.name,parsed.data.sourceType,parsed.data.leadDays,parsed.data.severity,parsed.data.targetRole,user.id]);await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'notification_rule.created','notification_rule',$3,'{}')`,[user.tenantId,user.id,result.rows[0].id]);const rule=(await c.query(`${ruleSelect} WHERE id=$1`,[result.rows[0].id])).rows[0];return reply.code(201).send({rule:shapeRule(rule)});});});
 app.patch("/rules/:id",{preHandler:[requireSession,allow("owner","admin")]},async(request,reply)=>{const id=(request.params as any).id,parsed=updateNotificationRuleSchema.safeParse(request.body);if(!id||!parsed.success)return reply.code(400).send({error:"INVALID_NOTIFICATION_RULE_UPDATE"});const user=request.sessionUser;const changed=await withTenantTransaction(user.tenantId,user.id,async c=>(await c.query(`UPDATE notification_rules SET status=$2,updated_at=now() WHERE id=$1`,[id,parsed.data.status])).rowCount);return changed?reply.code(204).send():reply.code(404).send({error:"NOTIFICATION_RULE_NOT_FOUND"});});
 app.post("/generate",{preHandler:[requireSession,allow("owner","admin","operator")]},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>{const tenant=request.sessionUser.tenantId;const sources:{type:string;sql:string}[]=[
  {type:"maintenance",sql:`SELECT p.id,'Yaklaşan bakım: '||p.title,'Bakım hedefi yaklaşıyor',p.vehicle_id,p.due_date FROM vehicle_maintenance_plans p WHERE p.status='scheduled'`},
  {type:"document",sql:`SELECT d.id,'Araç belgesi yenileme','Belge geçerlilik süresi yaklaşıyor',d.vehicle_id,d.expires_on FROM vehicle_documents d WHERE d.status='active' AND d.expires_on IS NOT NULL`},
  {type:"action",sql:`SELECT a.id,'Aksiyon bekliyor: '||a.title,'Atanan aksiyonun son tarihi yaklaşıyor',a.vehicle_id,a.due_on FROM action_items a WHERE a.status IN ('open','in_progress') AND a.due_on IS NOT NULL`},
  {type:"safety_event",sql:`SELECT s.id,'Kritik sürücü güvenliği olayı','Yüksek önem seviyeli olay inceleme bekliyor',a.vehicle_id,s.occurred_at::date FROM driver_safety_events s JOIN vehicle_assignments a ON a.id=s.assignment_id WHERE s.status<>'resolved' AND s.severity IN ('high','critical')`},
  {type:"incident",sql:`SELECT i.id,'Açık kaza/hasar dosyası','Olay dosyası inceleme bekliyor',i.vehicle_id,i.occurred_at::date FROM vehicle_incidents i WHERE i.status IN ('open','reviewing')`}
 ];let created=0;
 for(const source of sources){const rules=(await c.query(`SELECT id,lead_days,severity,target_role FROM notification_rules WHERE status='active' AND source_type=$1`,[source.type])).rows;for(const rule of rules){const result=await c.query(`INSERT INTO in_app_notifications(tenant_id,rule_id,source_type,source_id,title,message,severity,vehicle_id,recipient_user_id) SELECT $1,$2,$3,x.id,x.title,x.message,$4,x.vehicle_id,m.user_id FROM (${source.sql}) x JOIN memberships m ON m.tenant_id=$1 AND ($5::text IS NULL OR m.role=$5) WHERE x.due_on<=CURRENT_DATE+$6::integer ON CONFLICT(tenant_id,rule_id,source_type,source_id,recipient_user_id) DO NOTHING`,[tenant,rule.id,source.type,rule.severity,rule.target_role,rule.lead_days]);created+=result.rowCount??0;}}
 await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'notifications.generated','notification_center',$2,jsonb_build_object('created',$3))`,[tenant,request.sessionUser.id,created]);return{created};}));
 app.get("/",{preHandler:requireSession},async(request,reply)=>{const parsed=notificationQuerySchema.safeParse(request.query);if(!parsed.success)return reply.code(400).send({error:"INVALID_NOTIFICATION_QUERY"});const user=request.sessionUser;return withTenantTransaction(user.tenantId,user.id,async c=>{const params:any[]=[user.id];let where=` WHERE n.recipient_user_id=$1 AND (n.source_type<>'provider_incident' OR EXISTS(SELECT 1 FROM memberships m WHERE m.tenant_id=n.tenant_id AND m.user_id=$1 AND m.role IN ('owner','admin','operator')))`;if(parsed.data.status==="archived")where+=` AND n.archived_at IS NOT NULL`;else{where+=` AND n.archived_at IS NULL`;if(parsed.data.status!=="all"){params.push(parsed.data.status==="unread");where+=` AND (n.read_at IS NULL)=$${params.length}`;}}if(parsed.data.severity){params.push(parsed.data.severity);where+=` AND n.severity=$${params.length}`;}const rows=(await c.query(`${notificationSelect}${where} ORDER BY n.read_at NULLS FIRST,n.created_at DESC`,params)).rows;const unread=(await c.query(`SELECT count(*)::integer AS count FROM in_app_notifications n WHERE n.recipient_user_id=$1 AND n.archived_at IS NULL AND n.read_at IS NULL AND (n.source_type<>'provider_incident' OR EXISTS(SELECT 1 FROM memberships m WHERE m.tenant_id=n.tenant_id AND m.user_id=$1 AND m.role IN ('owner','admin','operator')))`,[user.id])).rows[0].count;return{notifications:rows.map(shapeNotification),unread};});});
 app.patch("/read-all",{preHandler:requireSession},async(request,reply)=>{const user=request.sessionUser;const updated=await withTenantTransaction(user.tenantId,user.id,async c=>{const result=await c.query(`UPDATE in_app_notifications n SET read_at=now() WHERE n.recipient_user_id=$1 AND n.archived_at IS NULL AND n.read_at IS NULL AND (n.source_type<>'provider_incident' OR EXISTS(SELECT 1 FROM memberships m WHERE m.tenant_id=n.tenant_id AND m.user_id=$1 AND m.role IN ('owner','admin','operator')))`,[user.id]);await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'notifications.read_all','notification_center',$2,jsonb_build_object('updated',$3))`,[user.tenantId,user.id,result.rowCount??0]);return result.rowCount??0;});return reply.send({updated});});
 app.get("/retention",{preHandler:[requireSession,allow("owner","admin","operator")]},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>{const settings=await loadNotificationRetentionState(c);const runs=(await c.query(`SELECT id,run_key AS "runKey",source,cutoff_at AS "cutoffAt",retention_days AS "retentionDays",batch_size AS "batchSize",archived_count AS "archivedCount",initiated_by AS "initiatedBy",created_at AS "createdAt" FROM notification_archive_runs ORDER BY created_at DESC LIMIT 10`)).rows;const attempts=(await c.query(`SELECT id,run_key AS "runKey",source,status,outcome_code AS "outcomeCode",retry_of_attempt_id AS "retryOfAttemptId",retry_number AS "retryNumber",initiated_by AS "initiatedBy",archived_count AS "archivedCount",eligible_remaining AS "eligibleRemaining",started_at AS "startedAt",heartbeat_at AS "heartbeatAt",completed_at AS "completedAt",reconciled_at AS "reconciledAt",reconciled_by AS "reconciledBy",reconciliation_id AS "reconciliationId",created_at AS "createdAt" FROM notification_archive_attempts ORDER BY created_at DESC LIMIT 20`)).rows;const reconciliations=(await c.query(`SELECT id,reconciliation_key AS "reconciliationKey",source,stale_after_minutes AS "staleAfterMinutes",reconciled_count AS "reconciledCount",initiated_by AS "initiatedBy",created_at AS "createdAt" FROM notification_archive_reconciliations ORDER BY created_at DESC LIMIT 20`)).rows;return{settings,eligibleCount:await countEligibleNotifications(c,settings.readRetentionDays),recentRuns:runs.map(shapeArchiveRun),recentAttempts:attempts.map(row=>({...row,startedAt:row.startedAt.toISOString(),heartbeatAt:row.heartbeatAt.toISOString(),completedAt:row.completedAt?.toISOString()??null,reconciledAt:row.reconciledAt?.toISOString()??null,createdAt:row.createdAt.toISOString()})),recentReconciliations:reconciliations.map(shapeReconciliation)};}));
 app.put("/retention",{preHandler:[requireSession,allow("owner","admin")]},async(request,reply)=>{const parsed=updateNotificationRetentionSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_NOTIFICATION_RETENTION"});const user=request.sessionUser;return withTenantTransaction(user.tenantId,user.id,async c=>{const p=parsed.data;await c.query(`INSERT INTO notification_retention_settings(tenant_id,read_retention_days,automatic_archive_enabled,archive_interval_hours,archive_batch_size,automatic_reconciliation_enabled,reconciliation_interval_minutes,reconciliation_stale_after_minutes,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(tenant_id) DO UPDATE SET read_retention_days=$2,automatic_archive_enabled=$3,archive_interval_hours=$4,archive_batch_size=$5,automatic_reconciliation_enabled=$6,reconciliation_interval_minutes=$7,reconciliation_stale_after_minutes=$8,updated_by=$9,updated_at=now()`,[user.tenantId,p.readRetentionDays,p.automaticArchiveEnabled,p.archiveIntervalHours,p.archiveBatchSize,p.automaticReconciliationEnabled,p.reconciliationIntervalMinutes,p.reconciliationStaleAfterMinutes,user.id]);await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'notification_retention.updated','notification_retention',$1,$3::jsonb)`,[user.tenantId,user.id,JSON.stringify(p)]);return reply.code(204).send();});});
 app.post("/archive",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const user=request.sessionUser;const result=await executeNotificationArchiveAttempt({tenantId:user.tenantId,actorUserId:user.id,runKey:`manual:${randomUUID()}`,source:"manual",force:true});return reply.code(result.accepted&&result.failed?503:result.accepted?202:409).send(result);});
 app.post("/retention/reconcile",{preHandler:[requireSession,allow("owner","admin")]},async(request,reply)=>{const parsed=manualReconcileNotificationArchiveSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"RECONCILIATION_CONFIRMATION_REQUIRED"});const user=request.sessionUser;const minuteBucket=Math.floor(Date.now()/60_000);const result=await reconcileStaleNotificationArchiveAttempts({tenantId:user.tenantId,actorUserId:user.id,reconciliationKey:`manual:${user.id}:${minuteBucket}`,source:"manual",force:true});if(!result.accepted)return reply.code(result.reason==="duplicate"?200:result.reason==="archive_in_progress"?409:400).send(result);return reply.code(result.reconciledCount>0?202:200).send(result);});
 app.post("/retention/attempts/:attemptId/retry",{preHandler:[requireSession,allow("owner","admin")]},async(request,reply)=>{const parsed=retryNotificationArchiveSchema.safeParse(request.params);if(!parsed.success)return reply.code(400).send({error:"INVALID_NOTIFICATION_ARCHIVE_RETRY"});const user=request.sessionUser;const result=await executeNotificationArchiveAttempt({tenantId:user.tenantId,actorUserId:user.id,runKey:`retry:${parsed.data.attemptId}:${randomUUID()}`,source:"retry",force:true,retryOfAttemptId:parsed.data.attemptId});if(!result.accepted)return reply.code(result.reason==="retry_not_allowed"||result.reason==="duplicate"?409:400).send(result);return reply.code(result.failed?503:202).send(result);});
 app.patch("/:id/read",{preHandler:requireSession},async(request,reply)=>{const user=request.sessionUser,id=(request.params as any).id;const changed=await withTenantTransaction(user.tenantId,user.id,async c=>(await c.query(`UPDATE in_app_notifications n SET read_at=COALESCE(read_at,now()) WHERE n.id=$1 AND n.recipient_user_id=$2 AND n.archived_at IS NULL AND (n.source_type<>'provider_incident' OR EXISTS(SELECT 1 FROM memberships m WHERE m.tenant_id=n.tenant_id AND m.user_id=$2 AND m.role IN ('owner','admin','operator')))`,[id,user.id])).rowCount);return changed?reply.code(204).send():reply.code(404).send({error:"NOTIFICATION_NOT_FOUND"});});
}
