import type {FastifyInstance} from "fastify";
import {createNotificationProviderSchema,updateNotificationProviderSchema} from "@filo/contracts";
import {withTenantTransaction} from "@filo/database";import {requireSession} from "../lib/auth.js";import {allow} from "../lib/permissions.js";
const guard={preHandler:[requireSession,allow("owner","admin")]};
const select=`SELECT id,name,channel,provider,credential_env_ref AS "credentialEnvRef",webhook_secret_env_ref AS "webhookSecretEnvRef",status,created_at AS "createdAt" FROM notification_provider_profiles`;const shape=(r:any)=>({...r,createdAt:r.createdAt.toISOString()});
export async function notificationProviderRoutes(app:FastifyInstance){
 app.get("/",guard,async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>({providers:(await c.query(`${select} ORDER BY channel,name`)).rows.map(shape)})));
 app.post("/",guard,async(request,reply)=>{const parsed=createNotificationProviderSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_NOTIFICATION_PROVIDER"});const u=request.sessionUser,p=parsed.data;return withTenantTransaction(u.tenantId,u.id,async c=>{if(p.status==="active")await c.query(`UPDATE notification_provider_profiles SET status='inactive',updated_at=now() WHERE channel=$1 AND status='active'`,[p.channel]);const row=(await c.query(`INSERT INTO notification_provider_profiles(tenant_id,name,channel,provider,credential_env_ref,webhook_secret_env_ref,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[u.tenantId,p.name,p.channel,p.provider,p.credentialEnvRef,p.webhookSecretEnvRef,p.status,u.id])).rows[0];await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'notification_provider.created','notification_provider',$3,jsonb_build_object('channel',$4,'provider',$5))`,[u.tenantId,u.id,row.id,p.channel,p.provider]);return reply.code(201).send({provider:shape((await c.query(`${select} WHERE id=$1`,[row.id])).rows[0])});});});
 app.patch("/:id",guard,async(request,reply)=>{const id=(request.params as any).id,parsed=updateNotificationProviderSchema.safeParse(request.body);if(!id||!parsed.success)return reply.code(400).send({error:"INVALID_PROVIDER_UPDATE"});const u=request.sessionUser;return withTenantTransaction(u.tenantId,u.id,async c=>{const current=(await c.query(`SELECT channel FROM notification_provider_profiles WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!current)return reply.code(404).send({error:"PROVIDER_NOT_FOUND"});if(parsed.data.status==="active")await c.query(`UPDATE notification_provider_profiles SET status='inactive',updated_at=now() WHERE channel=$1 AND id<>$2`,[current.channel,id]);await c.query(`UPDATE notification_provider_profiles SET status=$2,updated_at=now() WHERE id=$1`,[id,parsed.data.status]);return reply.code(204).send();});});
}
