import type {FastifyInstance} from "fastify";
import {createNotificationTemplateSchema,previewNotificationTemplateSchema,updateNotificationTemplateSchema} from "@filo/contracts";
import {withTenantTransaction} from "@filo/database";
import {requireSession} from "../lib/auth.js";
import {allow} from "../lib/permissions.js";
import {renderTemplate,templateVariables} from "../lib/template-renderer.js";

const select=`SELECT id,key,channel,locale,subject_template AS "subjectTemplate",body_template AS "bodyTemplate",required_variables AS "requiredVariables",status,created_at AS "createdAt" FROM notification_templates`;
const shape=(row:any)=>({...row,createdAt:row.createdAt.toISOString()});
export async function notificationTemplateRoutes(app:FastifyInstance){
 app.get("/",{preHandler:[requireSession,allow("owner","admin","operator")]},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async c=>({templates:(await c.query(`${select} ORDER BY key,channel,locale`)).rows.map(shape)})));
 app.post("/",{preHandler:[requireSession,allow("owner","admin")]},async(request,reply)=>{const parsed=createNotificationTemplateSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_NOTIFICATION_TEMPLATE"});const user=request.sessionUser,p=parsed.data;const used=templateVariables(`${p.subjectTemplate} ${p.bodyTemplate}`);if(used.some(key=>!p.requiredVariables.includes(key)))return reply.code(400).send({error:"UNDECLARED_TEMPLATE_VARIABLE"});return withTenantTransaction(user.tenantId,user.id,async c=>{const row=(await c.query(`INSERT INTO notification_templates(tenant_id,key,channel,locale,subject_template,body_template,required_variables,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[user.tenantId,p.key,p.channel,p.locale,p.subjectTemplate,p.bodyTemplate,p.requiredVariables,user.id])).rows[0];await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'notification_template.created','notification_template',$3,jsonb_build_object('key',$4,'channel',$5,'locale',$6))`,[user.tenantId,user.id,row.id,p.key,p.channel,p.locale]);return reply.code(201).send({template:shape((await c.query(`${select} WHERE id=$1`,[row.id])).rows[0])});});});
 app.post("/preview",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const parsed=previewNotificationTemplateSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_TEMPLATE_PREVIEW"});try{return{subject:renderTemplate(parsed.data.subjectTemplate,parsed.data.variables),body:renderTemplate(parsed.data.bodyTemplate,parsed.data.variables)};}catch(error){return reply.code(400).send({error:error instanceof Error?error.message:"TEMPLATE_RENDER_FAILED"});}});
 app.patch("/:id",{preHandler:[requireSession,allow("owner","admin")]},async(request,reply)=>{const id=(request.params as any).id,parsed=updateNotificationTemplateSchema.safeParse(request.body);if(!id||!parsed.success)return reply.code(400).send({error:"INVALID_TEMPLATE_UPDATE"});const user=request.sessionUser;const changed=await withTenantTransaction(user.tenantId,user.id,async c=>(await c.query(`UPDATE notification_templates SET status=$2,updated_at=now() WHERE id=$1`,[id,parsed.data.status])).rowCount);return changed?reply.code(204).send():reply.code(404).send({error:"TEMPLATE_NOT_FOUND"});});
}

