import type { FastifyInstance } from "fastify";
import { createTireSetSchema,mountTireSetSchema,removeTireSetSchema } from "@filo/contracts";
import { withTenantTransaction } from "@filo/database";
import { requireSession } from "../lib/auth.js";
import { allow } from "../lib/permissions.js";

const selectTires=`SELECT t.id,t.brand,t.model,t.size,t.serial_number AS "serialNumber",t.purchased_on AS "purchasedOn",t.initial_odometer_km AS "initialOdometerKm",t.target_life_km AS "targetLifeKm",t.target_change_date AS "targetChangeDate",t.notes,t.status,m.vehicle_id AS "vehicleId",v.plate AS "vehiclePlate",m.position,m.mounted_on AS "mountedOn",m.mounted_odometer_km AS "mountedOdometerKm",odo.current_odometer_km AS "currentOdometerKm",CASE WHEN odo.current_odometer_km IS NULL OR m.mounted_odometer_km IS NULL THEN NULL ELSE odo.current_odometer_km-m.mounted_odometer_km END AS "usedKm",CASE WHEN t.target_life_km IS NULL OR odo.current_odometer_km IS NULL OR m.mounted_odometer_km IS NULL THEN NULL ELSE t.target_life_km-(odo.current_odometer_km-m.mounted_odometer_km) END AS "remainingKm",CASE WHEN t.status='retired' THEN 'retired' WHEN t.status='stored' THEN 'stored' WHEN (t.target_change_date<CURRENT_DATE OR (t.target_life_km IS NOT NULL AND odo.current_odometer_km-m.mounted_odometer_km>=t.target_life_km)) THEN 'overdue' WHEN (t.target_change_date<=CURRENT_DATE+INTERVAL '30 days' OR (t.target_life_km IS NOT NULL AND t.target_life_km-(odo.current_odometer_km-m.mounted_odometer_km)<=2000)) THEN 'due_soon' ELSE 'mounted' END AS "displayStatus",t.created_at AS "createdAt" FROM tire_sets t LEFT JOIN tire_mounts m ON m.tire_set_id=t.id AND m.removed_on IS NULL LEFT JOIN vehicles v ON v.id=m.vehicle_id LEFT JOIN LATERAL (SELECT max(e.odometer_km)::int AS current_odometer_km FROM vehicle_expenses e WHERE e.vehicle_id=m.vehicle_id) odo ON true`;

export async function tireRoutes(app:FastifyInstance){
  app.get("/",{preHandler:requireSession},async request=>withTenantTransaction(request.sessionUser.tenantId,request.sessionUser.id,async client=>{
    const rows=(await client.query(`${selectTires} ORDER BY CASE t.status WHEN 'mounted' THEN 0 WHEN 'stored' THEN 1 ELSE 2 END,t.created_at DESC`)).rows;
    const tires=rows.map(r=>({...r,purchasedOn:r.purchasedOn?.toISOString().slice(0,10)??null,targetChangeDate:r.targetChangeDate?.toISOString().slice(0,10)??null,mountedOn:r.mountedOn?.toISOString().slice(0,10)??null,initialOdometerKm:r.initialOdometerKm===null?null:Number(r.initialOdometerKm),targetLifeKm:r.targetLifeKm===null?null:Number(r.targetLifeKm),mountedOdometerKm:r.mountedOdometerKm===null?null:Number(r.mountedOdometerKm),currentOdometerKm:r.currentOdometerKm===null?null:Number(r.currentOdometerKm),usedKm:r.usedKm===null?null:Number(r.usedKm),remainingKm:r.remainingKm===null?null:Number(r.remainingKm),createdAt:r.createdAt.toISOString()}));
    return {tires,summary:{total:tires.length,mounted:tires.filter(x=>x.status==='mounted').length,dueSoon:tires.filter(x=>x.displayStatus==='due_soon').length,overdue:tires.filter(x=>x.displayStatus==='overdue').length}};
  }));
  app.post("/",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{
    const parsed=createTireSetSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_TIRE_SET"});const u=request.sessionUser;
    try{const id=await withTenantTransaction(u.tenantId,u.id,async c=>{const r=(await c.query(`INSERT INTO tire_sets(tenant_id,brand,model,size,serial_number,purchased_on,initial_odometer_km,target_life_km,target_change_date,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`,[u.tenantId,parsed.data.brand,parsed.data.model,parsed.data.size,parsed.data.serialNumber,parsed.data.purchasedOn,parsed.data.initialOdometerKm,parsed.data.targetLifeKm,parsed.data.targetChangeDate,parsed.data.notes,u.id])).rows[0];await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'tire_set.created','tire_set',$3,jsonb_build_object('brand',$4,'model',$5))`,[u.tenantId,u.id,r.id,parsed.data.brand,parsed.data.model]);return r.id;});return reply.code(201).send({tireSetId:id});}catch(e){if((e as {code?:string}).code==='23505')return reply.code(409).send({error:"TIRE_SERIAL_EXISTS"});throw e;}
  });
  app.post("/:id/mount",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const {id}=request.params as {id:string},p=mountTireSetSchema.safeParse(request.body);if(!p.success)return reply.code(400).send({error:"INVALID_TIRE_MOUNT"});const u=request.sessionUser;const ok=await withTenantTransaction(u.tenantId,u.id,async c=>{const v=await c.query("SELECT 1 FROM vehicles WHERE id=$1 AND status<>'inactive'",[p.data.vehicleId]);if(!v.rowCount)return false;const t=await c.query("UPDATE tire_sets SET status='mounted',updated_at=now() WHERE id=$1 AND status='stored'",[id]);if(!t.rowCount)return false;await c.query(`INSERT INTO tire_mounts(tenant_id,tire_set_id,vehicle_id,position,mounted_on,mounted_odometer_km) VALUES($1,$2,$3,$4,$5,$6)`,[u.tenantId,id,p.data.vehicleId,p.data.position,p.data.mountedOn,p.data.mountedOdometerKm]);await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'tire_set.mounted','tire_set',$3,jsonb_build_object('vehicleId',$4,'position',$5))`,[u.tenantId,u.id,id,p.data.vehicleId,p.data.position]);return true;});return ok?reply.code(204).send():reply.code(404).send({error:"STORED_TIRE_OR_VEHICLE_NOT_FOUND"});});
  app.post("/:id/remove",{preHandler:[requireSession,allow("owner","admin","operator")]},async(request,reply)=>{const {id}=request.params as {id:string},p=removeTireSetSchema.safeParse(request.body);if(!p.success)return reply.code(400).send({error:"INVALID_TIRE_REMOVAL"});const u=request.sessionUser;const ok=await withTenantTransaction(u.tenantId,u.id,async c=>{const r=await c.query(`UPDATE tire_mounts SET removed_on=$2,removed_odometer_km=$3,removal_reason=$4 WHERE tire_set_id=$1 AND removed_on IS NULL AND $2>=mounted_on AND $3>=mounted_odometer_km RETURNING vehicle_id`,[id,p.data.removedOn,p.data.removedOdometerKm,p.data.reason]);if(!r.rowCount)return false;await c.query("UPDATE tire_sets SET status='stored',updated_at=now() WHERE id=$1",[id]);await c.query(`INSERT INTO audit_events(tenant_id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'tire_set.removed','tire_set',$3,jsonb_build_object('vehicleId',$4,'reason',$5))`,[u.tenantId,u.id,id,r.rows[0].vehicle_id,p.data.reason]);return true;});return ok?reply.code(204).send():reply.code(404).send({error:"ACTIVE_TIRE_MOUNT_NOT_FOUND"});});
}
