import { bulkImportRecords, requirePrivilegedAccess, requireWorkspace, rollbackMigrationRun, runtimeEnv } from "../../../lib/platform-store";
import { assertRequestSize, assertSameOrigin, enforceRateLimit } from "../../../lib/security";
import { apiErrorResponse } from "../../../lib/api-errors";

export const dynamic="force-dynamic";

function parseLine(line:string,delimiter:string){const cells:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){cells.push(value.trim());value=""}else value+=char}cells.push(value.trim());return cells}
function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(line=>line.trim());if(lines.length<2)throw new Response("CSV başlık ve en az bir veri satırı içermelidir.",{status:400});const delimiter=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?";":",";const headers=parseLine(lines[0],delimiter).map(value=>value.trim());if(headers.some(value=>!value))throw new Response("CSV başlıklarında boş alan bulunamaz.",{status:400});return lines.slice(1).map(line=>Object.fromEntries(headers.map((header,index)=>[header,parseLine(line,delimiter)[index]||""])))}
function errorResponse(error:unknown){return apiErrorResponse(error,"Toplu aktarım başarısız.")}

export async function POST(request:Request){try{assertSameOrigin(request);assertRequestSize(request,1_100_000);const workspace=await requireWorkspace(false);await enforceRateLimit(runtimeEnv().DB,request,"bulk-import",10,600,workspace.email);const payload=await request.json() as Record<string,unknown>;if(payload.action==="rollback"){await requirePrivilegedAccess(workspace,"rollback-data-migration");return Response.json(await rollbackMigrationRun(workspace,String(payload.migrationRunId||"")))}if(payload.commit===true)await requirePrivilegedAccess(workspace,"commit-data-migration");const text=String(payload.csv||"");if(text.length>1_000_000)return Response.json({error:"CSV en fazla 1 MB olabilir."},{status:413});const rows=parseCsv(text);const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));const sourceSha256=[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,"0")).join("");return Response.json(await bulkImportRecords(workspace,{module:String(payload.module||""),rows,commit:payload.commit===true,sourceSha256}))}catch(error){return errorResponse(error)}}
