import { createHash, createHmac, randomUUID } from "node:crypto";
import net from "node:net";

const required=["FILO_API_BASE","FILO_DEVICE_TOKEN","FILO_PROVIDER","FILO_PROTOCOL","FILO_VEHICLE_ID"];
for(const key of required)if(!process.env[key])throw new Error(`${key} zorunludur.`);
const config={apiBase:process.env.FILO_API_BASE.replace(/\/$/,""),token:process.env.FILO_DEVICE_TOKEN,provider:process.env.FILO_PROVIDER.toUpperCase(),protocol:process.env.FILO_PROTOCOL.toUpperCase(),vehicleId:process.env.FILO_VEHICLE_ID.toUpperCase(),port:Number(process.env.LISTEN_PORT||5027),queclink:process.env.QUECLINK_PROFILE_JSON?JSON.parse(process.env.QUECLINK_PROFILE_JSON):null};
if(!["TELTONIKA","QUECLINK"].includes(config.provider))throw new Error("FILO_PROVIDER TELTONIKA veya QUECLINK olmalıdır.");

const readUInt=(buffer,offset,length)=>length===1?buffer.readUInt8(offset):length===2?buffer.readUInt16BE(offset):length===4?buffer.readUInt32BE(offset):Number(buffer.readBigUInt64BE(offset));
const crc16Ibm=buffer=>{let crc=0;for(const byte of buffer){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc&1)?(crc>>>1)^0xa001:crc>>>1}return crc&0xffff};
const skipIo=(buffer,offset,codec)=>{const wide=codec===0x8e;offset+=wide?4:2;for(const bytes of [1,2,4,8]){const count=readUInt(buffer,offset,wide?2:1);offset+=wide?2:1;offset+=count*((wide?2:1)+bytes)}if(wide){const count=readUInt(buffer,offset,2);offset+=2;for(let index=0;index<count;index++){offset+=2;const length=readUInt(buffer,offset,2);offset+=2+length}}return offset};
function parseTeltonika(packet){if(packet.length<12||packet.readUInt32BE(0)!==0)throw new Error("Teltonika preamble geçersiz.");const dataLength=packet.readUInt32BE(4);if(packet.length<8+dataLength+4)throw new Error("Teltonika paket uzunluğu eksik.");const data=packet.subarray(8,8+dataLength),expectedCrc=packet.readUInt32BE(8+dataLength)&0xffff,actualCrc=crc16Ibm(data);if(expectedCrc!==actualCrc)throw new Error(`Teltonika CRC uyuşmuyor: ${expectedCrc}/${actualCrc}`);const codec=data.readUInt8(0);if(![0x08,0x8e].includes(codec))throw new Error(`Desteklenmeyen Teltonika codec: 0x${codec.toString(16)}`);const count=data.readUInt8(1),records=[];let offset=2;for(let index=0;index<count;index++){const capturedAt=new Date(Number(data.readBigUInt64BE(offset))).toISOString();offset+=8;const priority=data.readUInt8(offset++),longitude=data.readInt32BE(offset)/1e7;offset+=4;const latitude=data.readInt32BE(offset)/1e7;offset+=4;const altitude=data.readInt16BE(offset);offset+=2;const heading=data.readUInt16BE(offset);offset+=2;const satellites=data.readUInt8(offset++),speed=data.readUInt16BE(offset);offset+=2;offset=skipIo(data,offset,codec);records.push({vehicleId:config.vehicleId,latitude,longitude,altitude,heading,speed,battery:0,accuracy:satellites?Math.max(3,Math.round(60/satellites)):0,eventType:priority>0?"PRIORITY_LOCATION":"LOCATION",sequence:index,capturedAt})}if(data.readUInt8(offset)!==count)throw new Error("Teltonika kayıt adedi sonlandırıcısı uyuşmuyor.");return records}
function parseQueclink(line){if(!config.queclink)throw new Error("QUECLINK_PROFILE_JSON olmadan Queclink satırı ayrıştırılmaz.");const fields=line.trim().replace(/\$$/,"").split(","),at=key=>fields[Number(config.queclink[key])];const latitude=Number(at("latitude")),longitude=Number(at("longitude")),speed=Number(at("speed")||0),altitude=Number(at("altitude")||0),heading=Number(at("heading")||0),rawTime=String(at("timestamp")||"");if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||!/^\d{14}$/.test(rawTime))throw new Error("Queclink profil eşlemesi geçersiz veri üretti.");const capturedAt=new Date(`${rawTime.slice(0,4)}-${rawTime.slice(4,6)}-${rawTime.slice(6,8)}T${rawTime.slice(8,10)}:${rawTime.slice(10,12)}:${rawTime.slice(12,14)}Z`).toISOString();return [{vehicleId:config.vehicleId,latitude,longitude,speed,altitude,heading,battery:0,accuracy:0,eventType:line.includes("GTFRI")?"LOCATION":"DEVICE_EVENT",sequence:0,capturedAt}]}
async function publish(records){const body=JSON.stringify({provider:config.provider,protocol:config.protocol,vehicleId:config.vehicleId,records}),sentAt=new Date().toISOString(),messageId=`${config.provider.toLowerCase()}-${randomUUID()}`,signature=createHmac("sha256",config.token).update(`${sentAt}.${messageId}.${body}`).digest("hex");const response=await fetch(`${config.apiBase}/api/tracker-gateway`,{method:"POST",headers:{Authorization:`Bearer ${config.token}`,"Content-Type":"application/json","X-Filo-Sent-At":sentAt,"X-Filo-Message-Id":messageId,"X-Filo-Signature":signature},body});const result=await response.text();if(!response.ok)throw new Error(`Filo gateway ${response.status}: ${result}`);return {messageId,payloadSha256:createHash("sha256").update(body).digest("hex")}}

const server=net.createServer(socket=>{let buffer=Buffer.alloc(0),imeiAccepted=false;socket.on("data",async chunk=>{socket.pause();try{buffer=Buffer.concat([buffer,chunk]);if(config.provider==="TELTONIKA"){if(!imeiAccepted){if(buffer.length<2){socket.resume();return}const length=buffer.readUInt16BE(0);if(buffer.length<2+length){socket.resume();return}const imei=buffer.subarray(2,2+length).toString("ascii");if(!/^\d{15}$/.test(imei))throw new Error("Teltonika IMEI geçersiz.");buffer=buffer.subarray(2+length);imeiAccepted=true;socket.write(Buffer.from([1]))}while(buffer.length>=12){const dataLength=buffer.readUInt32BE(4),packetLength=8+dataLength+4;if(buffer.length<packetLength)break;const packet=buffer.subarray(0,packetLength),records=parseTeltonika(packet);await publish(records);const ack=Buffer.alloc(4);ack.writeUInt32BE(records.length);socket.write(ack);buffer=buffer.subarray(packetLength)}}else{const text=buffer.toString("utf8"),lines=text.split(/\r?\n|\$/);buffer=Buffer.from(lines.pop()||"");for(const line of lines.filter(Boolean)){await publish(parseQueclink(`${line}$`));socket.write(Buffer.from("+SACK:GTHBD,OK$"))}}socket.resume()}catch(error){console.error(new Date().toISOString(),error instanceof Error?error.message:error);socket.destroy()}});socket.on("error",error=>console.error(new Date().toISOString(),error.message))});
server.listen(config.port,"0.0.0.0",()=>console.log(`Filo ${config.provider} bridge ${config.port} portunda hazır.`));
